{   'ACCOUNT NAME': 23,
    'ACCOUNT/EVENT IDENTIFIER': 562,
    'ACTIVITY/EVENT NAME': 1,
    'ACTIVITY/EVENT TOTAL YTD': 562,
    'ADMINISTRATIVE RATIO APPLIES': 3,
    'AFFILIATED - DATE FORM F1 FILED': 1,
    'AFFILIATED CANDIDATE ID NUM': 1,
    'AFFILIATED CITY': 1,
    'AFFILIATED COMMITTEE FEC ID': 1,
    'AFFILIATED COMMITTEE NAME': 1,
    'AFFILIATED Committee ID NUM': 1,
    'AFFILIATED Committee NAME': 1,
    'AFFILIATED FIRST NAME': 1,
    'AFFILIATED LAST NAME': 1,
    'AFFILIATED MIDDLE NAME': 1,
    'AFFILIATED PREFIX': 1,
    'AFFILIATED RELATIONSHIP CODE': 1,
    'AFFILIATED STATE': 1,
    'AFFILIATED STREET 1': 1,
    'AFFILIATED STREET 2': 1,
    'AFFILIATED SUFFIX': 1,
    'AFFILIATED ZIP': 1,
    'AGENT CITY': 1,
    'AGENT FIRST NAME': 1,
    'AGENT LAST NAME': 1,
    'AGENT MIDDLE NAME': 1,
    'AGENT PREFIX': 1,
    'AGENT STATE': 1,
    'AGENT STREET 1': 1,
    'AGENT STREET 2': 1,
    'AGENT SUFFIX': 1,
    'AGENT TELEPHONE': 1,
    'AGENT TITLE': 1,
    'AGENT ZIP': 1,
    'AGGREGATE GENERAL ELEC EXPENDED': 81,
    'ALABAMA': 20,
    'ALASKA': 20,
    'ARIZONA': 20,
    'ARKANSAS': 20,
    'Activity GOTV': 1,
    'Activity Is Voter ID': 1,
    'Activity Is Voter Registration': 1,
    'Activity is Administrative - Only': 561,
    'Activity is Direct Candidate Support': 561,
    'Activity is Direct Fundraising': 561,
    'Activity is Generic Campaign': 1,
    'Activity is Generic Voter Drive - Only': 561,
    'Activity is Party Public Communications Made by PAC': 561,
    'Activity is an Exempt Activity': 561,
    'All Loans Received': 85,
    'All Other Loans': 37,
    'All Other Political Committees (PACS)': 37,
    'BACK REFERENCE SCHED / FORM NAME': 76,
    'BACK REFERENCE SCHED NAME': 20370,
    'BACK REFERENCE TRAN ID': 22,
    'BACK REFERENCE TRAN ID NUMBER': 20446,
    'BALANCE AT CLOSE (This Period)': 165,
    'BANK CITY': 1,
    'BANK NAME': 1,
    'BANK STATE': 1,
    'BANK STREET 1': 1,
    'BANK STREET 2': 1,
    'BANK ZIP': 1,
    'BEGINNING BALANCE (This Period)': 165,
    'BENEFICIARY CANDIDATE DISTRICT': 8371,
    'BENEFICIARY CANDIDATE FEC ID': 8371,
    'BENEFICIARY CANDIDATE FIRST NAME': 8371,
    'BENEFICIARY CANDIDATE LAST NAME': 8371,
    'BENEFICIARY CANDIDATE MIDDLE NAME': 8371,
    'BENEFICIARY CANDIDATE OFFICE': 8371,
    'BENEFICIARY CANDIDATE PREFIX': 8371,
    'BENEFICIARY CANDIDATE STATE': 8371,
    'BENEFICIARY CANDIDATE SUFFIX': 8371,
    'BENEFICIARY COMMITTEE FEC ID': 8371,
    'BENEFICIARY COMMITTEE NAME': 8371,
    'CALENDAR Y-T-D (per election/office)': 8,
    'CALIFORNIA': 20,
    'CANDIDATE DIST': 1,
    'CANDIDATE DISTRICT': 2,
    'CANDIDATE FIRST NAME': 3,
    'CANDIDATE ID NUMBER': 3,
    'CANDIDATE LAST NAME': 3,
    'CANDIDATE MIDDLE NAME': 3,
    'CANDIDATE OFFICE': 3,
    'CANDIDATE PREFIX': 3,
    'CANDIDATE STATE': 3,
    'CANDIDATE SUFFIX': 3,
    'CASH ON HAND (Beginning)': 1,
    'CASH ON HAND AT CLOSE ...': 36,
    'CASH ON HAND as of Jan 1': 1,
    'CATEGORY CODE': 9022,
    'CHANGE OF ADDRESS': 122,
    'CHANGE OF COMMITTEE EMAIL': 1,
    'CHANGE OF COMMITTEE NAME': 1,
    'CHANGE OF COMMITTEE WEB URL': 1,
    'CITY': 124,
    'COLORADO': 20,
    'COMMITTEE EMAIL': 1,
    'COMMITTEE NAME': 124,
    'COMMITTEE TYPE': 2,
    'COMMITTEE WEB URL': 1,
    'COMPLETING FIRST NAME': 8,
    'COMPLETING LAST NAME': 8,
    'COMPLETING MIDDLE NAME': 8,
    'COMPLETING PREFIX': 8,
    'COMPLETING SUFFIX': 8,
    'CONDUIT CITY': 19719,
    'CONDUIT NAME': 19719,
    'CONDUIT STATE': 19719,
    'CONDUIT STREET 1': 8371,
    'CONDUIT STREET 2': 8371,
    'CONDUIT STREET1': 11348,
    'CONDUIT STREET2': 11348,
    'CONDUIT ZIP': 19719,
    'CONNECTICUT': 20,
    'CONTRIBUTION AGGREGATE': 11348,
    'CONTRIBUTION AMOUNT': 98,
    'CONTRIBUTION AMOUNT (F3L Bundled)': 11348,
    'CONTRIBUTION DATE': 11446,
    'CONTRIBUTION PURPOSE CODE': 11348,
    'CONTRIBUTION PURPOSE DESCRIP': 11348,
    'CONTRIBUTOR CITY': 11446,
    'CONTRIBUTOR COMMITTEE FEC ID': 98,
    'CONTRIBUTOR EMPLOYER': 11446,
    'CONTRIBUTOR FIRST NAME': 11446,
    'CONTRIBUTOR LAST NAME': 11446,
    'CONTRIBUTOR MIDDLE NAME': 11446,
    'CONTRIBUTOR OCCUPATION': 11446,
    'CONTRIBUTOR ORGANIZATION NAME': 11446,
    'CONTRIBUTOR PREFIX': 11446,
    'CONTRIBUTOR STATE': 11446,
    'CONTRIBUTOR STREET 1': 11446,
    'CONTRIBUTOR STREET 2': 11446,
    'CONTRIBUTOR SUFFIX': 11446,
    'CONTRIBUTOR ZIP': 11446,
    'COVERAGE FROM DATE': 122,
    'COVERAGE THROUGH DATE': 122,
    'CREDITOR CITY': 165,
    'CREDITOR FIRST NAME': 165,
    'CREDITOR LAST NAME': 165,
    'CREDITOR MIDDLE NAME': 165,
    'CREDITOR ORGANIZATION NAME': 165,
    'CREDITOR PREFIX': 165,
    'CREDITOR STATE': 165,
    'CREDITOR STREET 1': 165,
    'CREDITOR STREET 2': 165,
    'CREDITOR SUFFIX': 165,
    'CREDITOR ZIP': 165,
    'CUSTODIAN CITY': 1,
    'CUSTODIAN FIRST NAME': 1,
    'CUSTODIAN LAST NAME': 1,
    'CUSTODIAN MIDDLE NAME': 1,
    'CUSTODIAN PREFIX': 1,
    'CUSTODIAN STATE': 1,
    'CUSTODIAN STREET 1': 1,
    'CUSTODIAN STREET 2': 1,
    'CUSTODIAN SUFFIX': 1,
    'CUSTODIAN TELEPHONE': 1,
    'CUSTODIAN TITLE': 1,
    'CUSTODIAN ZIP': 1,
    'Cash Beginning Reporting Period': 36,
    'Cash on Hand Close': 85,
    'Cash on Hand Jan 1, 19': 85,
    'Cash on Hand at Close': 85,
    'Cash on Hand beginning': 85,
    'Cash on hand at Close Period': 36,
    'Cmte Met Requirements': 1,
    'Contributions to Federal Candidates/Committees': 85,
    'Coordinated Expend made by Party Committees': 85,
    'DATE OF CONTRIBUTION': 1,
    'DATE OF ELECTION': 121,
    'DATE SIGNED': 132,
    'DEBTS BY (Totals from SCH C and/or D)': 36,
    'DEBTS TO ( Totals from SCH C and/or D)': 36,
    'DELAWARE': 20,
    'DESIGNATING COMMITTEE ID NUMBER': 81,
    'DESIGNATING COMMITTEE NAME': 81,
    'DISBURSEMENTS': 1,
    'DIST OF COLUMBIA': 20,
    'DONOR CANDIDATE DISTRICT': 11348,
    'DONOR CANDIDATE FEC ID': 11348,
    'DONOR CANDIDATE FIRST NAME': 11348,
    'DONOR CANDIDATE LAST NAME': 11348,
    'DONOR CANDIDATE MIDDLE NAME': 11348,
    'DONOR CANDIDATE OFFICE': 11348,
    'DONOR CANDIDATE PREFIX': 11348,
    'DONOR CANDIDATE STATE': 11348,
    'DONOR CANDIDATE SUFFIX': 11348,
    'DONOR COMMITTEE FEC ID': 11348,
    'DONOR COMMITTEE NAME': 11348,
    'Date - Day after General Election': 20,
    'Date - General Election': 20,
    'Debts by': 85,
    'Debts to': 85,
    'Direct Candidate Support?': 1,
    'Direct Fundraising?': 1,
    'ELECTION CODE': 19867,
    'ELECTION DISTRICT': 36,
    'ELECTION OTHER DESCRIPTION': 19751,
    'ELECTION STATE': 36,
    'ENDING CASH ON HAND': 1,
    'ENTITY TYPE': 20657,
    'EVENT TYPE': 22,
    'EVENT/ACTIVITY ID/NAME': 22,
    'EXPENDITURE AMOUNT': 89,
    'EXPENDITURE AMOUNT (F3L Bundled)': 8371,
    'EXPENDITURE DATE': 9022,
    'EXPENDITURE PURPOSE CODE': 9022,
    'EXPENDITURE PURPOSE DESCRIP': 9022,
    'Exempt Legal and Accounting Disbursements': 20,
    'FEDERAL PERCENT': 3,
    'FEDERAL PERCENTAGE': 1,
    'FEDERAL SHARE': 562,
    'FILER COMMITTEE ID': 1,
    'FILER COMMITTEE ID NUMBER': 20878,
    'FLAT MINIMUM FEDERAL PERCENTAGE': 3,
    'FLORIDA': 20,
    'FORM TYPE': 20804,
    'Federal Funds': 20,
    'Federal Share': 85,
    'Fundraising': 20,
    'Fundraising Disbursements': 20,
    'GENERIC VOTER DRIVE RATIO APPLIES': 3,
    'GEORGIA': 20,
    'GOTV DISBURSEMENTS': 1,
    'GUAM': 20,
    'GUARANTEED AMOUNT': 1,
    'GUARANTOR CITY': 1,
    'GUARANTOR EMPLOYER': 1,
    'GUARANTOR FIRST NAME': 1,
    'GUARANTOR LAST NAME': 1,
    'GUARANTOR MIDDLE NAME': 1,
    'GUARANTOR OCCUPATION': 1,
    'GUARANTOR PREFIX': 1,
    'GUARANTOR STATE': 1,
    'GUARANTOR STREET 1': 1,
    'GUARANTOR STREET 2': 1,
    'GUARANTOR SUFFIX': 1,
    'GUARANTOR ZIP': 1,
    'Generic Campaign DISBURSEMENTS': 1,
    'HAWAII': 20,
    'Has filer been designated to make Coordinated Expenditures?': 81,
    'IDAHO': 20,
    'ILLINOIS': 20,
    'INCURRED AMOUNT (This Period)': 165,
    'INDIANA': 20,
    'IOWA': 20,
    'Independent Expenditures': 85,
    'Individual Contribution Total': 36,
    'Individuals': 20,
    'Individuals Itemized': 37,
    'Individuals Total': 37,
    'Individuals Unitemized': 37,
    'Individuals/Persons': 85,
    'Itemized': 85,
    'Itemized Receipts From Persons': 1,
    'KANSAS': 20,
    'KENTUCKY': 20,
    'LEADERSHIP PAC': 1,
    'LENDER CANDIDATE DISTRICT': 27,
    'LENDER CANDIDATE FIRST NAME': 27,
    'LENDER CANDIDATE ID NUMBER': 27,
    'LENDER CANDIDATE LAST NAME': 27,
    'LENDER CANDIDATE MIDDLE NM': 27,
    'LENDER CANDIDATE OFFICE': 27,
    'LENDER CANDIDATE PREFIX': 27,
    'LENDER CANDIDATE STATE': 27,
    'LENDER CANDIDATE SUFFIX': 27,
    'LENDER CITY': 27,
    'LENDER COMMITTEE ID NUMBER': 27,
    'LENDER FIRST NAME': 27,
    'LENDER LAST NAME': 27,
    'LENDER MIDDLE NAME': 27,
    'LENDER ORGANIZATION NAME': 27,
    'LENDER PREFIX': 27,
    'LENDER STATE': 27,
    'LENDER STREET 1': 27,
    'LENDER STREET 2': 27,
    'LENDER SUFFIX': 27,
    'LENDER ZIP': 27,
    'LEVIN SHARE': 1,
    'LOAN AMOUNT (Original)': 27,
    'LOAN BALANCE': 27,
    'LOAN INTEREST RATE % (Terms)': 27,
    'LOAN PAYMENT TO DATE': 27,
    'LOBBYIST/REGISTRANT PAC': 1,
    'LOUISIANA': 20,
    'Legal and Accounting': 20,
    'Line 4 Total': 1,
    'Loan Repayment By Candidate': 37,
    'Loan Repayments': 85,
    'Loan Repayments Made': 85,
    'Loan Repayments Received': 85,
    'Loan Repayments, ALL Other Loans': 37,
    'Loan Repayments, All Other Loans': 36,
    'Loans Made': 85,
    'Loans made or guarn. by the Candidate': 37,
    'MAINE': 20,
    'MARYLAND': 20,
    'MASSACHUSETTS': 20,
    'MEMO CODE': 20394,
    'MEMO TEXT/DESCRIPTION': 20394,
    'MICHIGAN': 20,
    'MINNESOTA': 20,
    'MISSISSIPPI': 20,
    'MISSOURI': 20,
    'MONTANA': 20,
    'Made or Guaranteed by the Candidate': 20,
    'NEBRASKA': 20,
    'NET Operating Expenditures.': 37,
    'NEVADA': 20,
    'NEW HAMPSHIRE': 20,
    'NEW JERSEY': 20,
    'NEW MEXICO': 20,
    'NEW YORK': 20,
    'NONFEDERAL PERCENT': 3,
    'NONFEDERAL PERCENTAGE': 1,
    'NONFEDERAL SHARE': 561,
    'NORTH CAROLINA': 20,
    'NORTH DAKOTA': 20,
    'Net Contributions': 122,
    'Net Expenditures': 20,
    'Net Operating Expenditures': 85,
    'Net contributions': 85,
    'Non-Allocable 100% Fed Election Activity': 85,
    'Non-Federal Share': 85,
    'OHIO': 20,
    'OKLAHOMA': 20,
    'OREGON': 20,
    'ORGANIZATION TYPE': 1,
    'OTHER DISBURSEMENTS': 1,
    'OTHER RECEIPTS': 1,
    'Of 51st Contributor': 1,
    'Of Loans made or guar. by the Cand.': 36,
    'Of Orig Registration': 1,
    'Offsets to Operating Expenditures': 122,
    'Offsets to Operating Expenditures (refunds)': 85,
    'Operating': 20,
    'Operating Expenditures': 37,
    'Other Disbursements': 122,
    'Other Federal Operating Expenditures': 85,
    'Other Federal Receipts (dividends)': 85,
    'Other Loans': 20,
    'Other Political Committees': 122,
    'Other Political Committees (PACs)': 105,
    'Other Receipts': 37,
    'Other Repayments': 20,
    'PARTY CODE': 1,
    'PARTY TYPE': 1,
    'PAYEE CANDIDATE DISTRICT': 81,
    'PAYEE CANDIDATE FIRST NAME': 81,
    'PAYEE CANDIDATE ID NUMBER': 81,
    'PAYEE CANDIDATE LAST NAME': 81,
    'PAYEE CANDIDATE MIDDLE NAME': 81,
    'PAYEE CANDIDATE OFFICE': 81,
    'PAYEE CANDIDATE PREFIX': 81,
    'PAYEE CANDIDATE STATE': 81,
    'PAYEE CANDIDATE SUFFIX': 81,
    'PAYEE CITY': 9022,
    'PAYEE COMMITTEE ID NUMBER': 81,
    'PAYEE Committee FEC ID NUMBER': 8,
    'PAYEE FIRST NAME': 9022,
    'PAYEE LAST NAME': 9022,
    'PAYEE MIDDLE NAME': 9022,
    'PAYEE ORGANIZATION NAME': 9022,
    'PAYEE PREFIX': 9022,
    'PAYEE STATE': 9022,
    'PAYEE STREET 1': 9022,
    'PAYEE STREET 2': 9022,
    'PAYEE SUFFIX': 9022,
    'PAYEE ZIP': 9022,
    'PAYMENT AMOUNT (This Period)': 165,
    'PENNSYLVANIA': 20,
    'PUBLIC COMMUNICATIONS REFERENCING PARTY ONLY RATIO APPLIES': 3,
    'PUERTO RICO': 20,
    'PURPOSE OF DEBT OR OBLIGATION': 165,
    'Personal Funds': 27,
    'Political Party Committees': 122,
    'Political Party committees': 85,
    'QUALIFIED COMMITTEE': 85,
    'RATIO CODE': 1,
    'REC TYPE': 76,
    'RECEIPT DATE': 22,
    'RECEIPT LINE NUMBER': 27,
    'RECEIPTS': 1,
    'RECORD ID NUMBER (for account name)': 1,
    'REPORT CODE': 121,
    'RHODE ISLAND': 20,
    'Received from or Guaranteed by Candidate': 20,
    'Reference to SI or SL system code that identifies the Account': 19719,
    'Refund, Other Political Committees': 37,
    'Refund, Political Party Committees': 37,
    'Refund/Individuals Other than Political Committees': 37,
    'Refund/Other Political Committees': 36,
    'Refund/Political Party Committees': 36,
    'Refunds of Federal Contributions': 85,
    'S/O CANDIDATE DISTRICT': 8,
    'S/O CANDIDATE FIRST NAME': 8,
    'S/O CANDIDATE ID NUMBER': 8,
    'S/O CANDIDATE LAST NAME': 8,
    'S/O CANDIDATE OFFICE': 8,
    'S/O CANDIDATE PREFIX': 8,
    'S/O CANDIDATE STATE': 8,
    'S/O CANDIDATE SUFFIX': 8,
    'S/O CANDINATE MIDDLE NAME': 8,
    'SEMI-ANNUAL REFUNDED BUNDLED AMT': 8371,
    'SIGNATURE FIRST NAME': 1,
    'SIGNATURE LAST NAME': 1,
    'SIGNATURE MIDDLE NAME': 1,
    'SIGNATURE PREFIX': 1,
    'SIGNATURE SUFFIX': 1,
    'SIGNER FIRST NAME': 1,
    'SIGNER LAST NAME': 1,
    'SIGNER MIDDLE NAME': 1,
    'SIGNER PREFIX': 1,
    'SIGNER SUFFIX': 1,
    'SOUTH CAROLINA': 20,
    'SOUTH DAKOTA': 20,
    'STATE': 124,
    'STATE OF ELECTION': 121,
    'STREET 1': 124,
    'STREET 2': 124,
    'SUBMISSION DATE': 1,
    'SUBORDINATE CITY': 81,
    'SUBORDINATE COMMITTEE ID NUMBER': 81,
    'SUBORDINATE COMMITTEE NAME': 81,
    'SUBORDINATE STATE': 81,
    'SUBORDINATE STREET 1': 81,
    'SUBORDINATE STREET 2': 81,
    'SUBORDINATE ZIP': 81,
    'SUBTOTAL': 1,
    'SUPPORT/OPPOSE CODE': 8,
    'Secured?': 27,
    'Shared Federal Activity (H6) Fed Share': 85,
    'Shared Federal Activity (H6) Non-Fed': 85,
    'State and Local Party Committee Non-Presidential and Non-Senate Election': 3,
    'State and Local Party Committee Presidential and Senate Election Year (36%': 3,
    'State and Local Party Committee Presidential-Only Election Year (28% Federal)': 3,
    'State and Local Party Committee Senate-Only Election Year (21% Federal)': 3,
    'Subtotal': 85,
    'Subtotals': 36,
    'TENNESSEE': 20,
    'TEXAS': 20,
    'TEXT4000': 76,
    'TOTAL AMOUNT TRANSFERRED': 22,
    'TOTAL DISBURSEMENTS': 1,
    'TOTAL FED-LEVIN AMOUNT': 1,
    'TOTAL FED-NONFED AMOUNT': 561,
    'TOTAL RECEIPTS': 1,
    'TOTALS': 20,
    'TRANSACTION ID': 11348,
    'TRANSACTION ID NUMBER': 9412,
    'TRANSFERRED AMOUNT': 22,
    'TREASURER CITY': 1,
    'TREASURER FIRST NAME': 123,
    'TREASURER LAST NAME': 123,
    'TREASURER MIDDLE NAME': 123,
    'TREASURER PREFIX': 123,
    'TREASURER STATE': 1,
    'TREASURER STREET 1': 1,
    'TREASURER STREET 2': 1,
    'TREASURER SUFFIX': 123,
    'TREASURER TELEPHONE': 1,
    'TREASURER TITLE': 1,
    'TREASURER ZIP': 1,
    'Terms': 27,
    'The Candidate': 37,
    'Total': 85,
    'Total Contribution Refunds': 122,
    'Total Contributions': 122,
    'Total Contributions (NO Loans)': 36,
    'Total Contributions (No Loans)': 37,
    'Total Contributions Refunds': 122,
    'Total Disbursements': 122,
    'Total Disbursements this Period': 36,
    'Total Federal Disbursements': 85,
    'Total Federal Election Activity': 85,
    'Total Federal Operating Expenditures': 85,
    'Total Federal Receipts': 85,
    'Total Loan Repayments': 37,
    'Total Loan Repayments Made': 20,
    'Total Loans': 37,
    'Total Non-Federal Transfers (18a+18b)': 85,
    'Total Offset to Operating Expenditures': 36,
    'Total Offsets to Operating Expenditures': 37,
    'Total Operating Expenditures': 122,
    'Total Receipts': 122,
    'Total Receipts From Persons': 1,
    'Total Receipts this Period': 36,
    'Total contributions (Other than Loans)': 20,
    'Total contributions Refunds': 85,
    'Total disbursements': 85,
    'Total operating Expenditures': 85,
    'Transfers From Aff/Other Party Committees': 20,
    'Transfers From Other AUTH Committees': 37,
    'Transfers From Other Authorized Committees': 36,
    'Transfers To Other AUTH Committees': 37,
    'Transfers from Affiliated/Other Party Committees': 85,
    'Transfers from Non-Federal (Levin - H5)': 85,
    'Transfers from Nonfederal Account (H3)': 85,
    'Transfers to Affiliated/Other Party Committees': 85,
    'Transfers to Other Authorized Committees': 37,
    'UTAH': 20,
    'Unitemized': 85,
    'Unitemized Receipts From Persons': 1,
    'VERMONT': 20,
    'VIRGIN ISLANDS': 20,
    'VIRGINIA': 20,
    'Voter ID DISBURSEMENTS': 1,
    'Voter Registration DISBURSEMENTS': 1,
    'WASHINGTON': 20,
    'WEST VIRGINIA': 20,
    'WISCONSIN': 20,
    'WYOMING': 20,
    'Year for Above': 85,
    'ZIP': 124,
    '_record_type': 20871,
    '_src_file': 21019}