def load() :
	 return {'name':u'''simple''', 'data'={   'ACCOUNT NAME': 369,
    'ACCOUNT/EVENT IDENTIFIER': 5482,
    'ACTIVITY PRIMARY': 2,
    'ACTIVITY/EVENT NAME': 27,
    'ACTIVITY/EVENT TOTAL YTD': 5491,
    'ADMINISTRATIVE RATIO APPLIES': 45,
    'AFFILIATED CANDIDATE ID NUM': 21,
    'AFFILIATED CITY': 64,
    'AFFILIATED COMMITTEE FEC ID': 4,
    'AFFILIATED COMMITTEE NAME': 4,
    'AFFILIATED Committee ID NUM': 64,
    'AFFILIATED Committee NAME': 64,
    'AFFILIATED FIRST NAME': 64,
    'AFFILIATED LAST NAME': 64,
    'AFFILIATED MIDDLE NAME': 64,
    'AFFILIATED PREFIX': 64,
    'AFFILIATED RELATIONSHIP CODE': 64,
    'AFFILIATED STATE': 64,
    'AFFILIATED STREET 1': 64,
    'AFFILIATED STREET 2': 64,
    'AFFILIATED SUFFIX': 64,
    'AFFILIATED ZIP': 64,
    'AGENT CITY': 64,
    'AGENT FIRST NAME': 64,
    'AGENT LAST NAME': 64,
    'AGENT MIDDLE NAME': 64,
    'AGENT PREFIX': 64,
    'AGENT STATE': 64,
    'AGENT STREET 1': 64,
    'AGENT STREET 2': 64,
    'AGENT SUFFIX': 64,
    'AGENT TELEPHONE': 64,
    'AGENT TITLE': 64,
    'AGENT ZIP': 64,
    'AGGREGATE GENERAL ELEC EXPENDED': 9,
    'ALABAMA': 2,
    'ALASKA': 2,
    'ARIZONA': 2,
    'ARKANSAS': 2,
    'AUTH CITY': 1,
    'AUTH COMMITTEE ID NUMBER': 7,
    'AUTH COMMITTEE NAME': 7,
    'AUTH STATE': 7,
    'AUTH STREET 1': 7,
    'AUTH STREET 2': 7,
    'AUTH ZIP': 7,
    'Activity GOTV': 1,
    'Activity Is Voter ID': 1,
    'Activity Is Voter Registration': 1,
    'Activity is Administrative - Only': 5490,
    'Activity is Direct Candidate Support': 5490,
    'Activity is Direct Fundraising': 5490,
    'Activity is Generic Campaign': 1,
    'Activity is Generic Voter Drive - Only': 5490,
    'Activity is Party Public Communications Made by PAC': 5490,
    'Activity is an Exempt Activity': 5490,
    'All Loans Received': 65,
    'All Other Loans': 18,
    'All Other Political Committees (PACS)': 100,
    'BACK REFERENCE SCHED / FORM NAME': 2748,
    'BACK REFERENCE SCHED NAME': 1292002,
    'BACK REFERENCE TRAN ID': 345,
    'BACK REFERENCE TRAN ID NUMBER': 1297777,
    'BALANCE AT CLOSE (This Period)': 596,
    'BANK CITY': 64,
    'BANK NAME': 64,
    'BANK STATE': 64,
    'BANK STREET 1': 64,
    'BANK STREET 2': 64,
    'BANK ZIP': 64,
    'BEGINNING BALANCE (This Period)': 596,
    'BENEFICIARY CANDIDATE DISTRICT': 507020,
    'BENEFICIARY CANDIDATE FEC ID': 507020,
    'BENEFICIARY CANDIDATE FIRST NAME': 507020,
    'BENEFICIARY CANDIDATE LAST NAME': 507020,
    'BENEFICIARY CANDIDATE MIDDLE NAME': 507020,
    'BENEFICIARY CANDIDATE OFFICE': 507020,
    'BENEFICIARY CANDIDATE PREFIX': 507020,
    'BENEFICIARY CANDIDATE STATE': 507020,
    'BENEFICIARY CANDIDATE SUFFIX': 507020,
    'BENEFICIARY COMMITTEE FEC ID': 507020,
    'BENEFICIARY COMMITTEE NAME': 507020,
    'CALENDAR Y-T-D (per election/office)': 37,
    'CALIFORNIA': 2,
    'CANDIDATE CITY': 6,
    'CANDIDATE DIST': 4,
    'CANDIDATE DISTRICT': 53,
    'CANDIDATE FIRST NAME': 59,
    'CANDIDATE ID NUMBER': 53,
    'CANDIDATE LAST NAME': 59,
    'CANDIDATE MIDDLE NAME': 59,
    'CANDIDATE OFFICE': 59,
    'CANDIDATE PARTY CODE': 6,
    'CANDIDATE PREFIX': 59,
    'CANDIDATE SIGNATURE FIRST NAME': 6,
    'CANDIDATE SIGNATURE LAST NAME': 6,
    'CANDIDATE SIGNATURE MIDDLE NAME': 6,
    'CANDIDATE SIGNATURE PREFIX': 6,
    'CANDIDATE SIGNATURE SUFFIX': 6,
    'CANDIDATE STATE': 59,
    'CANDIDATE STREET 1': 6,
    'CANDIDATE STREET 2': 6,
    'CANDIDATE SUFFIX': 59,
    'CANDIDATE ZIP': 6,
    'CASH ON HAND (Beginning)': 16,
    'CASH ON HAND AT CLOSE ...': 89,
    'CASH ON HAND as of Jan 1': 16,
    'CATEGORY CODE': 512557,
    'CHANGE OF ADDRESS': 888,
    'CHANGE OF COMMITTEE EMAIL': 46,
    'CHANGE OF COMMITTEE NAME': 46,
    'CHANGE OF COMMITTEE WEB URL': 46,
    'CITY': 893,
    'COLORADO': 2,
    'COMMITTEE EMAIL': 46,
    'COMMITTEE NAME': 893,
    'COMMITTEE TYPE': 50,
    'COMMITTEE WEB URL': 46,
    'COMPLETING FIRST NAME': 37,
    'COMPLETING LAST NAME': 37,
    'COMPLETING MIDDLE NAME': 37,
    'COMPLETING PREFIX': 37,
    'COMPLETING SUFFIX': 37,
    'CONDUIT CITY': 1289488,
    'CONDUIT NAME': 1289488,
    'CONDUIT STATE': 1289488,
    'CONDUIT STREET 1': 507020,
    'CONDUIT STREET 2': 507020,
    'CONDUIT STREET1': 782475,
    'CONDUIT STREET2': 782475,
    'CONDUIT ZIP': 1289488,
    'CONNECTICUT': 2,
    'CONTRIBUTION AGGREGATE F3L Semi-annual Bundled': 782475,
    'CONTRIBUTION AMOUNT': 7,
    'CONTRIBUTION AMOUNT (F3L Bundled)': 782475,
    'CONTRIBUTION DATE': 782482,
    'CONTRIBUTION PURPOSE CODE': 157732,
    'CONTRIBUTION PURPOSE DESCRIP': 782475,
    'CONTRIBUTOR CITY': 782482,
    'CONTRIBUTOR COMMITTEE FEC ID': 7,
    'CONTRIBUTOR EMPLOYER': 782482,
    'CONTRIBUTOR FIRST NAME': 782482,
    'CONTRIBUTOR LAST NAME': 782482,
    'CONTRIBUTOR MIDDLE NAME': 782482,
    'CONTRIBUTOR OCCUPATION': 782482,
    'CONTRIBUTOR ORGANIZATION NAME': 782482,
    'CONTRIBUTOR PREFIX': 782482,
    'CONTRIBUTOR STATE': 782482,
    'CONTRIBUTOR STREET 1': 782482,
    'CONTRIBUTOR STREET 2': 782482,
    'CONTRIBUTOR SUFFIX': 782482,
    'CONTRIBUTOR ZIP': 782482,
    'COVERAGE FROM DATE': 853,
    'COVERAGE THROUGH DATE': 853,
    'CREDITOR CITY': 596,
    'CREDITOR FIRST NAME': 596,
    'CREDITOR LAST NAME': 596,
    'CREDITOR MIDDLE NAME': 596,
    'CREDITOR ORGANIZATION NAME': 596,
    'CREDITOR PREFIX': 596,
    'CREDITOR STATE': 596,
    'CREDITOR STREET 1': 596,
    'CREDITOR STREET 2': 596,
    'CREDITOR SUFFIX': 596,
    'CREDITOR ZIP': 596,
    'CUSTODIAN CITY': 46,
    'CUSTODIAN FIRST NAME': 46,
    'CUSTODIAN LAST NAME': 46,
    'CUSTODIAN MIDDLE NAME': 46,
    'CUSTODIAN PREFIX': 46,
    'CUSTODIAN STATE': 46,
    'CUSTODIAN STREET 1': 46,
    'CUSTODIAN STREET 2': 46,
    'CUSTODIAN SUFFIX': 46,
    'CUSTODIAN TELEPHONE': 46,
    'CUSTODIAN TITLE': 46,
    'CUSTODIAN ZIP': 46,
    'Cash Beginning Reporting Period': 89,
    'Cash on Hand Beginning Period': 2,
    'Cash on Hand Close': 745,
    'Cash on Hand Close of Period': 2,
    'Cash on Hand Jan 1, 19': 745,
    'Cash on Hand at Close': 745,
    'Cash on Hand beginning': 745,
    'Cash on hand at Close Period': 89,
    'Cmte Met Requirements': 4,
    'Contributions to Federal Candidates/Committees': 745,
    'Coordinated Expend made by Party Committees': 745,
    'DATE OF CONTRIBUTION': 4,
    'DATE OF ELECTION': 837,
    'DATE SIGNED': 933,
    'DEBTS BY (Totals from SCH C and/or D)': 89,
    'DEBTS TO ( Totals from SCH C and/or D)': 89,
    'DELAWARE': 2,
    'DESIGNATING COMMITTEE ID NUMBER': 9,
    'DESIGNATING COMMITTEE NAME': 9,
    'DISBURSEMENTS': 16,
    'DIST OF COLUMBIA': 2,
    'DONOR CANDIDATE DISTRICT': 782475,
    'DONOR CANDIDATE FEC ID': 782475,
    'DONOR CANDIDATE FIRST NAME': 782475,
    'DONOR CANDIDATE LAST NAME': 782475,
    'DONOR CANDIDATE MIDDLE NAME': 782475,
    'DONOR CANDIDATE OFFICE': 782475,
    'DONOR CANDIDATE PREFIX': 782475,
    'DONOR CANDIDATE STATE': 782475,
    'DONOR CANDIDATE SUFFIX': 782475,
    'DONOR COMMITTEE FEC ID': 782475,
    'DONOR COMMITTEE NAME': 782475,
    'Date - Day after General Election': 11,
    'Date - General Election': 11,
    'Debts by': 747,
    'Debts to': 747,
    'Direct Candidate Support?': 27,
    'Direct Fundraising?': 27,
    'EFFECTIVE DATE': 46,
    'ELECTION CODE': 1290588,
    'ELECTION DISTRICT': 90,
    'ELECTION OTHER DESCRIPTION': 1289776,
    'ELECTION STATE': 90,
    'ENDING CASH ON HAND': 16,
    'ENTITY TYPE': 1295867,
    'EVENT TYPE': 345,
    'EVENT/ACTIVITY ID/NAME': 345,
    'EXPENDITURE AMOUNT': 46,
    'EXPENDITURE AMOUNT (F3L Bundled)': 507020,
    'EXPENDITURE DATE': 512557,
    'EXPENDITURE PURPOSE CODE': 91197,
    'EXPENDITURE PURPOSE DESCRIP': 512557,
    'Exempt Legal & Accounting Disbursement': 2,
    'Expenditures Subject to Limits': 2,
    'FEDERAL PERCENT': 45,
    'FEDERAL PERCENTAGE': 27,
    'FEDERAL SHARE': 5491,
    'FILER CANDIDATE ID NUMBER': 7,
    'FILER COMMITTEE ID': 16,
    'FILER COMMITTEE ID NUMBER': 1299927,
    'FLAT MINIMUM FEDERAL PERCENTAGE': 45,
    'FLORIDA': 2,
    'FORM TYPE': 1297201,
    'Federal Funds': 2,
    'Federal Share': 745,
    'Fundraising': 2,
    'Fundraising Disbursements': 2,
    'GENERIC CAMPAIGN AMOUNT': 8,
    'GENERIC VOTER DRIVE RATIO APPLIES': 45,
    'GEORGIA': 2,
    'GOTV AMOUNT': 8,
    'GOTV DISBURSEMENTS': 16,
    'GUAM': 2,
    'GUARANTEED AMOUNT': 1,
    'GUARANTOR CITY': 1,
    'GUARANTOR EMPLOYER': 1,
    'GUARANTOR FIRST NAME': 1,
    'GUARANTOR LAST NAME': 1,
    'GUARANTOR MIDDLE NAME': 1,
    'GUARANTOR OCCUPATION': 1,
    'GUARANTOR PREFIX': 1,
    'GUARANTOR STATE': 1,
    'GUARANTOR STREET 1': 1,
    'GUARANTOR STREET 2': 1,
    'GUARANTOR SUFFIX': 1,
    'GUARANTOR ZIP': 1,
    'Generic Campaign DISBURSEMENTS': 16,
    'HAWAII': 2,
    'Has filer been designated to make Coordinated Expenditures?': 9,
    'IDAHO': 2,
    'ILLINOIS': 2,
    'INCURRED AMOUNT (This Period)': 596,
    'INDIANA': 2,
    'IOWA': 2,
    'Independent Expenditures': 745,
    'Individual Contribution Total': 91,
    'Individuals': 2,
    'Individuals Itemized': 102,
    'Individuals Total': 100,
    'Individuals Unitemized': 102,
    'Individuals/Persons': 745,
    'Itemized': 745,
    'Itemized Receipts From Persons': 16,
    'Items on Hand to be Liquidated': 2,
    'JOINT FUND PARTICIPANT Committee FEC-ID': 18,
    'JOINT FUND PARTICIPANT Committee NAME': 18,
    'KANSAS': 2,
    'KENTUCKY': 2,
    'LEADERSHIP PAC': 46,
    'LENDER CANDIDATE DISTRICT': 253,
    'LENDER CANDIDATE FIRST NAME': 253,
    'LENDER CANDIDATE ID NUMBER': 253,
    'LENDER CANDIDATE LAST NAME': 253,
    'LENDER CANDIDATE MIDDLE NM': 253,
    'LENDER CANDIDATE OFFICE': 253,
    'LENDER CANDIDATE PREFIX': 253,
    'LENDER CANDIDATE STATE': 253,
    'LENDER CANDIDATE SUFFIX': 253,
    'LENDER CITY': 253,
    'LENDER COMMITTEE ID NUMBER': 253,
    'LENDER FIRST NAME': 253,
    'LENDER LAST NAME': 253,
    'LENDER MIDDLE NAME': 253,
    'LENDER ORGANIZATION NAME': 253,
    'LENDER PREFIX': 253,
    'LENDER STATE': 253,
    'LENDER STREET 1': 253,
    'LENDER STREET 2': 253,
    'LENDER SUFFIX': 253,
    'LENDER ZIP': 253,
    'LEVIN SHARE': 1,
    'LOAN AMOUNT (Original)': 253,
    'LOAN BALANCE': 253,
    'LOAN INTEREST RATE % (Terms)': 253,
    'LOAN PAYMENT TO DATE': 253,
    'LOBBYIST/REGISTRANT PAC': 46,
    'LOUISIANA': 2,
    'Legal and Accounting': 2,
    'Line 4 Total': 16,
    'Loan Repayment By Candidate': 100,
    'Loan Repayments': 745,
    'Loan Repayments Made': 745,
    'Loan Repayments Received': 745,
    'Loan Repayments, ALL Other Loans': 100,
    'Loan Repayments, All Other Loans': 89,
    'Loans Made': 745,
    'Loans made or guarn. by the Candidate': 100,
    'MAINE': 2,
    'MARYLAND': 2,
    'MASSACHUSETTS': 2,
    'MEMO CODE': 1295276,
    'MEMO TEXT/DESCRIPTION': 1295276,
    'MICHIGAN': 2,
    'MINNESOTA': 2,
    'MISSISSIPPI': 2,
    'MISSOURI': 2,
    'MONTANA': 2,
    'Made or Guaranteed by the Candidate': 2,
    'Made or guaranteed by Candidate': 2,
    'NEBRASKA': 2,
    'NET Operating Expenditures.': 100,
    'NEVADA': 2,
    'NEW HAMPSHIRE': 2,
    'NEW JERSEY': 2,
    'NEW MEXICO': 2,
    'NEW YORK': 2,
    'NON-FEDERAL PERCENTAGE': 5,
    'NONFEDERAL PERCENT': 45,
    'NONFEDERAL PERCENTAGE': 22,
    'NONFEDERAL SHARE': 5490,
    'NORTH CAROLINA': 2,
    'NORTH DAKOTA': 2,
    'Net Contributions': 847,
    'Net Operating Expenditures': 747,
    'Net contributions': 745,
    'Non-Allocable 100% Fed Election Activity': 745,
    'Non-Federal Share': 745,
    'OHIO': 2,
    'OKLAHOMA': 2,
    'OREGON': 2,
    'ORGANIZATION TYPE': 46,
    'ORIGINAL AMENDMENT DATE': 3,
    'OTHER DISBURSEMENTS': 16,
    'OTHER RECEIPTS': 16,
    'Of 51st Contributor': 4,
    'Of Loans made or guar. by the Cand.': 89,
    'Of Orig Registration': 4,
    'Offsets to Operating Expenditures': 845,
    'Offsets to Operating Expenditures (refunds)': 745,
    'Operating': 2,
    'Operating Expenditures': 102,
    'Other Disbursements': 847,
    'Other Federal Operating Expenditures': 745,
    'Other Federal Receipts (dividends)': 745,
    'Other Loans': 2,
    'Other Political Committees': 836,
    'Other Political Committees (PACs)': 747,
    'Other Receipts': 102,
    'Other Repayments': 2,
    'PARTY CODE': 46,
    'PARTY TYPE': 46,
    'PAYEE CANDIDATE DISTRICT': 9,
    'PAYEE CANDIDATE FIRST NAME': 9,
    'PAYEE CANDIDATE ID NUMBER': 9,
    'PAYEE CANDIDATE LAST NAME': 9,
    'PAYEE CANDIDATE MIDDLE NAME': 9,
    'PAYEE CANDIDATE OFFICE': 9,
    'PAYEE CANDIDATE PREFIX': 9,
    'PAYEE CANDIDATE STATE': 9,
    'PAYEE CANDIDATE SUFFIX': 9,
    'PAYEE CITY': 512557,
    'PAYEE COMMITTEE ID NUMBER': 9,
    'PAYEE Committee FEC ID NUMBER': 37,
    'PAYEE FIRST NAME': 512557,
    'PAYEE LAST NAME': 512557,
    'PAYEE MIDDLE NAME': 512557,
    'PAYEE ORGANIZATION NAME': 512557,
    'PAYEE PREFIX': 512557,
    'PAYEE STATE': 512557,
    'PAYEE STREET 1': 512557,
    'PAYEE STREET 2': 512557,
    'PAYEE SUFFIX': 512557,
    'PAYEE ZIP': 512557,
    'PAYMENT AMOUNT (This Period)': 596,
    'PCC CITY': 6,
    'PCC COMMITTEE ID NUMBER': 6,
    'PCC COMMITTEE NAME': 6,
    'PCC STATE': 6,
    'PCC STREET 1': 6,
    'PCC STREET 2': 6,
    'PCC ZIP': 6,
    'PENNSYLVANIA': 2,
    'PUBLIC COMMUNICATIONS REFERENCING PARTY ONLY RATIO APPLIES': 45,
    'PUERTO RICO': 2,
    'PURPOSE OF DEBT OR OBLIGATION': 596,
    'Personal Funds': 253,
    'Political Party Committees': 847,
    'Political Party committees': 745,
    'QTR/MON/POST BUNDLED CONTRIBUTIONS': 1,
    'QUALIFIED COMMITTEE': 745,
    'RATIO CODE': 27,
    'REC TYPE': 2753,
    'RECEIPT DATE': 353,
    'RECEIPT LINE NUMBER': 253,
    'RECEIPTS': 16,
    'RECORD ID NUMBER (for account name)': 16,
    'REPORT CODE': 837,
    'REPORT TYPE (24/48 Hour)': 3,
    'RHODE ISLAND': 2,
    'Received from or Guaranteed by Cand.': 2,
    'Reference to SI or SL system code that identifies the Account': 1289488,
    'Refund, Other Political Committees': 100,
    'Refund, Political Party Committees': 100,
    'Refund/Individuals Other than Political Committees': 100,
    'Refund/Other Political Committees': 89,
    'Refund/Political Party Committees': 89,
    'Refunds of Federal Contributions': 745,
    'S/O CANDIDATE DISTRICT': 37,
    'S/O CANDIDATE FIRST NAME': 37,
    'S/O CANDIDATE ID NUMBER': 37,
    'S/O CANDIDATE LAST NAME': 37,
    'S/O CANDIDATE OFFICE': 37,
    'S/O CANDIDATE PREFIX': 37,
    'S/O CANDIDATE STATE': 37,
    'S/O CANDIDATE SUFFIX': 37,
    'S/O CANDINATE MIDDLE NAME': 37,
    'SEMI-ANNUAL BUNDLED CONTRIBS': 1,
    'SEMI-ANNUAL JAN-JUN - Sect 6(b)': 1,
    'SEMI-ANNUAL JUL-DEC - Sect 6(b)': 1,
    'SEMI-ANNUAL PERIOD - Sect 5(c) or (d)': 1,
    'SEMI-ANNUAL REFUNDED BUNDLED AMT': 507020,
    'SIGNATURE FIRST NAME': 46,
    'SIGNATURE LAST NAME': 46,
    'SIGNATURE MIDDLE NAME': 46,
    'SIGNATURE PREFIX': 46,
    'SIGNATURE SUFFIX': 46,
    'SIGNER FIRST NAME': 3,
    'SIGNER LAST NAME': 3,
    'SIGNER MIDDLE NAME': 3,
    'SIGNER PREFIX': 3,
    'SIGNER SUFFIX': 3,
    'SOUTH CAROLINA': 2,
    'SOUTH DAKOTA': 2,
    'STATE': 893,
    'STATE OF ELECTION': 837,
    'STREET 1': 893,
    'STREET 2': 893,
    'SUBORDINATE CITY': 9,
    'SUBORDINATE COMMITTEE ID NUMBER': 9,
    'SUBORDINATE COMMITTEE NAME': 9,
    'SUBORDINATE STATE': 9,
    'SUBORDINATE STREET 1': 9,
    'SUBORDINATE STREET 2': 9,
    'SUBORDINATE ZIP': 9,
    'SUBTOTAL': 16,
    'SUPPORT/OPPOSE CODE': 37,
    'Secured?': 253,
    'Shared Federal Activity (H6) Fed Share': 745,
    'Shared Federal Activity (H6) Non-Fed': 745,
    'State and Local Party Committee Non-Presidential and Non-Senate Election': 45,
    'State and Local Party Committee Presidential and Senate Election Year (36%': 45,
    'State and Local Party Committee Presidential-Only Election Year (28% Federal)': 45,
    'State and Local Party Committee Senate-Only Election Year (21% Federal)': 45,
    'Subtotal': 747,
    'Subtotals': 89,
    'TENNESSEE': 2,
    'TEXAS': 2,
    'TEXT4000': 2753,
    'TOTAL AMOUNT TRANSFERRED': 353,
    'TOTAL DISBURSEMENTS': 16,
    'TOTAL FED-LEVIN AMOUNT': 1,
    'TOTAL FED-NONFED AMOUNT': 5490,
    'TOTAL RECEIPTS': 16,
    'TOTALS': 2,
    'TRANSACTION ID': 782475,
    'TRANSACTION ID NUMBER': 516587,
    'TRANSFERRED AMOUNT': 345,
    'TREASURER CITY': 46,
    'TREASURER FIRST NAME': 890,
    'TREASURER LAST NAME': 890,
    'TREASURER MIDDLE NAME': 890,
    'TREASURER PREFIX': 890,
    'TREASURER STATE': 46,
    'TREASURER STREET 1': 46,
    'TREASURER STREET 2': 46,
    'TREASURER SUFFIX': 890,
    'TREASURER TELEPHONE': 46,
    'TREASURER TITLE': 46,
    'TREASURER ZIP': 46,
    'Terms': 253,
    'The Candidate': 102,
    'Total': 745,
    'Total Contribution Refunds': 845,
    'Total Contributions': 847,
    'Total Contributions (NO Loans)': 89,
    'Total Contributions (No Loans)': 100,
    'Total Contributions Refunds': 847,
    'Total Disbursements': 847,
    'Total Disbursements this Period': 89,
    'Total Federal Disbursements': 745,
    'Total Federal Election Activity': 745,
    'Total Federal Operating Expenditures': 745,
    'Total Federal Receipts': 745,
    'Total Loan Repayments': 100,
    'Total Loan Repayments Made': 2,
    'Total Loans': 102,
    'Total Non-Federal Transfers (18a+18b)': 745,
    'Total Offset to Operating Expenditures': 89,
    'Total Offsets to Operating Expenditures': 102,
    'Total Operating Expenditures': 845,
    'Total Receipts': 847,
    'Total Receipts From Persons': 16,
    'Total Receipts this Period': 89,
    'Total contributions (Other than Loans)': 2,
    'Total contributions Refunds': 745,
    'Total disbursements': 745,
    'Total offsets to Expenditures': 2,
    'Total operating Expenditures': 745,
    'Transfers From Aff/Other Party Committees': 2,
    'Transfers From Other AUTH Committees': 100,
    'Transfers From Other Authorized Committees': 89,
    'Transfers To Other AUTH Committees': 100,
    'Transfers from Affiliated/Other Party Committees': 745,
    'Transfers from Non-Federal (Levin - H5)': 745,
    'Transfers from Nonfederal Account (H3)': 745,
    'Transfers to Affiliated/Other Party Committees': 745,
    'Transfers to Other Authorized Committees': 91,
    'UTAH': 2,
    'Unitemized': 745,
    'Unitemized Receipts From Persons': 16,
    'VERMONT': 2,
    'VIRGIN ISLANDS': 2,
    'VIRGINIA': 2,
    'VOTER ID AMOUNT': 8,
    'VOTER REGISTRATION AMOUNT': 8,
    'Voter ID DISBURSEMENTS': 16,
    'Voter Registration DISBURSEMENTS': 16,
    'WASHINGTON': 2,
    'WEST VIRGINIA': 2,
    'WISCONSIN': 2,
    'WYOMING': 2,
    'YEAR OF ELECTION 1900-2999': 6,
    'Year for Above': 745,
    'ZIP': 893,
    '_record_type': 1299896,
    '_src_file': 1300026}