def load() :
	 return {'name':u'''simple''', 'data'={   'ACCOUNT NAME': 335,
    'ACCOUNT/EVENT IDENTIFIER': 4943,
    'ACTIVITY PRIMARY': 2,
    'ACTIVITY/EVENT NAME': 23,
    'ACTIVITY/EVENT TOTAL YTD': 4952,
    'ADMINISTRATIVE RATIO APPLIES': 39,
    'AFFILIATED CANDIDATE ID NUM': 18,
    'AFFILIATED CITY': 53,
    'AFFILIATED COMMITTEE FEC ID': 4,
    'AFFILIATED COMMITTEE NAME': 4,
    'AFFILIATED Committee ID NUM': 53,
    'AFFILIATED Committee NAME': 53,
    'AFFILIATED FIRST NAME': 53,
    'AFFILIATED LAST NAME': 53,
    'AFFILIATED MIDDLE NAME': 53,
    'AFFILIATED PREFIX': 53,
    'AFFILIATED RELATIONSHIP CODE': 53,
    'AFFILIATED STATE': 53,
    'AFFILIATED STREET 1': 53,
    'AFFILIATED STREET 2': 53,
    'AFFILIATED SUFFIX': 53,
    'AFFILIATED ZIP': 53,
    'AGENT CITY': 53,
    'AGENT FIRST NAME': 53,
    'AGENT LAST NAME': 53,
    'AGENT MIDDLE NAME': 53,
    'AGENT PREFIX': 53,
    'AGENT STATE': 53,
    'AGENT STREET 1': 53,
    'AGENT STREET 2': 53,
    'AGENT SUFFIX': 53,
    'AGENT TELEPHONE': 53,
    'AGENT TITLE': 53,
    'AGENT ZIP': 53,
    'AGGREGATE GENERAL ELEC EXPENDED': 2,
    'ALABAMA': 2,
    'ALASKA': 2,
    'ARIZONA': 2,
    'ARKANSAS': 2,
    'AUTH CITY': 1,
    'AUTH COMMITTEE ID NUMBER': 7,
    'AUTH COMMITTEE NAME': 7,
    'AUTH STATE': 7,
    'AUTH STREET 1': 7,
    'AUTH STREET 2': 7,
    'AUTH ZIP': 7,
    'Activity GOTV': 1,
    'Activity Is Voter ID': 1,
    'Activity Is Voter Registration': 1,
    'Activity is Administrative - Only': 4951,
    'Activity is Direct Candidate Support': 4951,
    'Activity is Direct Fundraising': 4951,
    'Activity is Generic Campaign': 1,
    'Activity is Generic Voter Drive - Only': 4951,
    'Activity is Party Public Communications Made by PAC': 4951,
    'Activity is an Exempt Activity': 4951,
    'All Loans Received': 54,
    'All Other Loans': 17,
    'All Other Political Committees (PACS)': 98,
    'BACK REFERENCE SCHED / FORM NAME': 1415,
    'BACK REFERENCE SCHED NAME': 545443,
    'BACK REFERENCE TRAN ID': 328,
    'BACK REFERENCE TRAN ID NUMBER': 548071,
    'BALANCE AT CLOSE (This Period)': 517,
    'BANK CITY': 53,
    'BANK NAME': 53,
    'BANK STATE': 53,
    'BANK STREET 1': 53,
    'BANK STREET 2': 53,
    'BANK ZIP': 53,
    'BEGINNING BALANCE (This Period)': 517,
    'BENEFICIARY CANDIDATE DISTRICT': 207808,
    'BENEFICIARY CANDIDATE FEC ID': 207808,
    'BENEFICIARY CANDIDATE FIRST NAME': 207808,
    'BENEFICIARY CANDIDATE LAST NAME': 207808,
    'BENEFICIARY CANDIDATE MIDDLE NAME': 207808,
    'BENEFICIARY CANDIDATE OFFICE': 207808,
    'BENEFICIARY CANDIDATE PREFIX': 207808,
    'BENEFICIARY CANDIDATE STATE': 207808,
    'BENEFICIARY CANDIDATE SUFFIX': 207808,
    'BENEFICIARY COMMITTEE FEC ID': 207808,
    'BENEFICIARY COMMITTEE NAME': 207808,
    'CALENDAR Y-T-D (per election/office)': 29,
    'CALIFORNIA': 2,
    'CANDIDATE CITY': 6,
    'CANDIDATE DIST': 4,
    'CANDIDATE DISTRICT': 45,
    'CANDIDATE FIRST NAME': 51,
    'CANDIDATE ID NUMBER': 45,
    'CANDIDATE LAST NAME': 51,
    'CANDIDATE MIDDLE NAME': 51,
    'CANDIDATE OFFICE': 51,
    'CANDIDATE PARTY CODE': 6,
    'CANDIDATE PREFIX': 51,
    'CANDIDATE SIGNATURE FIRST NAME': 6,
    'CANDIDATE SIGNATURE LAST NAME': 6,
    'CANDIDATE SIGNATURE MIDDLE NAME': 6,
    'CANDIDATE SIGNATURE PREFIX': 6,
    'CANDIDATE SIGNATURE SUFFIX': 6,
    'CANDIDATE STATE': 51,
    'CANDIDATE STREET 1': 6,
    'CANDIDATE STREET 2': 6,
    'CANDIDATE SUFFIX': 51,
    'CANDIDATE ZIP': 6,
    'CASH ON HAND (Beginning)': 7,
    'CASH ON HAND AT CLOSE ...': 88,
    'CASH ON HAND as of Jan 1': 7,
    'CATEGORY CODE': 212791,
    'CHANGE OF ADDRESS': 726,
    'CHANGE OF COMMITTEE EMAIL': 38,
    'CHANGE OF COMMITTEE NAME': 38,
    'CHANGE OF COMMITTEE WEB URL': 38,
    'CITY': 730,
    'COLORADO': 2,
    'COMMITTEE EMAIL': 38,
    'COMMITTEE NAME': 730,
    'COMMITTEE TYPE': 42,
    'COMMITTEE WEB URL': 38,
    'COMPLETING FIRST NAME': 29,
    'COMPLETING LAST NAME': 29,
    'COMPLETING MIDDLE NAME': 29,
    'COMPLETING PREFIX': 29,
    'COMPLETING SUFFIX': 29,
    'CONDUIT CITY': 541672,
    'CONDUIT NAME': 541672,
    'CONDUIT STATE': 541672,
    'CONDUIT STREET 1': 207808,
    'CONDUIT STREET 2': 207808,
    'CONDUIT STREET1': 333870,
    'CONDUIT STREET2': 333870,
    'CONDUIT ZIP': 541672,
    'CONNECTICUT': 2,
    'CONTRIBUTION AGGREGATE F3L Semi-annual Bundled': 333870,
    'CONTRIBUTION AMOUNT': 7,
    'CONTRIBUTION AMOUNT (F3L Bundled)': 333870,
    'CONTRIBUTION DATE': 333877,
    'CONTRIBUTION PURPOSE CODE': 157732,
    'CONTRIBUTION PURPOSE DESCRIP': 333870,
    'CONTRIBUTOR CITY': 333877,
    'CONTRIBUTOR COMMITTEE FEC ID': 7,
    'CONTRIBUTOR EMPLOYER': 333877,
    'CONTRIBUTOR FIRST NAME': 333877,
    'CONTRIBUTOR LAST NAME': 333877,
    'CONTRIBUTOR MIDDLE NAME': 333877,
    'CONTRIBUTOR OCCUPATION': 333877,
    'CONTRIBUTOR ORGANIZATION NAME': 333877,
    'CONTRIBUTOR PREFIX': 333877,
    'CONTRIBUTOR STATE': 333877,
    'CONTRIBUTOR STREET 1': 333877,
    'CONTRIBUTOR STREET 2': 333877,
    'CONTRIBUTOR SUFFIX': 333877,
    'CONTRIBUTOR ZIP': 333877,
    'COVERAGE FROM DATE': 690,
    'COVERAGE THROUGH DATE': 690,
    'CREDITOR CITY': 517,
    'CREDITOR FIRST NAME': 517,
    'CREDITOR LAST NAME': 517,
    'CREDITOR MIDDLE NAME': 517,
    'CREDITOR ORGANIZATION NAME': 517,
    'CREDITOR PREFIX': 517,
    'CREDITOR STATE': 517,
    'CREDITOR STREET 1': 517,
    'CREDITOR STREET 2': 517,
    'CREDITOR SUFFIX': 517,
    'CREDITOR ZIP': 517,
    'CUSTODIAN CITY': 38,
    'CUSTODIAN FIRST NAME': 38,
    'CUSTODIAN LAST NAME': 38,
    'CUSTODIAN MIDDLE NAME': 38,
    'CUSTODIAN PREFIX': 38,
    'CUSTODIAN STATE': 38,
    'CUSTODIAN STREET 1': 38,
    'CUSTODIAN STREET 2': 38,
    'CUSTODIAN SUFFIX': 38,
    'CUSTODIAN TELEPHONE': 38,
    'CUSTODIAN TITLE': 38,
    'CUSTODIAN ZIP': 38,
    'Cash Beginning Reporting Period': 88,
    'Cash on Hand Beginning Period': 2,
    'Cash on Hand Close': 592,
    'Cash on Hand Close of Period': 2,
    'Cash on Hand Jan 1, 19': 592,
    'Cash on Hand at Close': 592,
    'Cash on Hand beginning': 592,
    'Cash on hand at Close Period': 88,
    'Cmte Met Requirements': 4,
    'Contributions to Federal Candidates/Committees': 592,
    'Coordinated Expend made by Party Committees': 592,
    'DATE OF CONTRIBUTION': 4,
    'DATE OF ELECTION': 683,
    'DATE SIGNED': 763,
    'DEBTS BY (Totals from SCH C and/or D)': 88,
    'DEBTS TO ( Totals from SCH C and/or D)': 88,
    'DELAWARE': 2,
    'DESIGNATING COMMITTEE ID NUMBER': 2,
    'DESIGNATING COMMITTEE NAME': 2,
    'DISBURSEMENTS': 7,
    'DIST OF COLUMBIA': 2,
    'DONOR CANDIDATE DISTRICT': 333870,
    'DONOR CANDIDATE FEC ID': 333870,
    'DONOR CANDIDATE FIRST NAME': 333870,
    'DONOR CANDIDATE LAST NAME': 333870,
    'DONOR CANDIDATE MIDDLE NAME': 333870,
    'DONOR CANDIDATE OFFICE': 333870,
    'DONOR CANDIDATE PREFIX': 333870,
    'DONOR CANDIDATE STATE': 333870,
    'DONOR CANDIDATE SUFFIX': 333870,
    'DONOR COMMITTEE FEC ID': 333870,
    'DONOR COMMITTEE NAME': 333870,
    'Date - Day after General Election': 10,
    'Date - General Election': 10,
    'Debts by': 594,
    'Debts to': 594,
    'Direct Candidate Support?': 23,
    'Direct Fundraising?': 23,
    'EFFECTIVE DATE': 38,
    'ELECTION CODE': 542603,
    'ELECTION DISTRICT': 89,
    'ELECTION OTHER DESCRIPTION': 541942,
    'ELECTION STATE': 89,
    'ENDING CASH ON HAND': 7,
    'ENTITY TYPE': 547408,
    'EVENT TYPE': 328,
    'EVENT/ACTIVITY ID/NAME': 328,
    'EXPENDITURE AMOUNT': 31,
    'EXPENDITURE AMOUNT (F3L Bundled)': 207808,
    'EXPENDITURE DATE': 212791,
    'EXPENDITURE PURPOSE CODE': 91197,
    'EXPENDITURE PURPOSE DESCRIP': 212791,
    'Exempt Legal & Accounting Disbursement': 2,
    'Expenditures Subject to Limits': 2,
    'FEDERAL PERCENT': 39,
    'FEDERAL PERCENTAGE': 23,
    'FEDERAL SHARE': 4952,
    'FILER CANDIDATE ID NUMBER': 7,
    'FILER COMMITTEE ID': 7,
    'FILER COMMITTEE ID NUMBER': 549934,
    'FLAT MINIMUM FEDERAL PERCENTAGE': 39,
    'FLORIDA': 2,
    'FORM TYPE': 548536,
    'Federal Funds': 2,
    'Federal Share': 592,
    'Fundraising': 2,
    'Fundraising Disbursements': 2,
    'GENERIC VOTER DRIVE RATIO APPLIES': 39,
    'GEORGIA': 2,
    'GOTV DISBURSEMENTS': 7,
    'GUAM': 2,
    'GUARANTEED AMOUNT': 1,
    'GUARANTOR CITY': 1,
    'GUARANTOR EMPLOYER': 1,
    'GUARANTOR FIRST NAME': 1,
    'GUARANTOR LAST NAME': 1,
    'GUARANTOR MIDDLE NAME': 1,
    'GUARANTOR OCCUPATION': 1,
    'GUARANTOR PREFIX': 1,
    'GUARANTOR STATE': 1,
    'GUARANTOR STREET 1': 1,
    'GUARANTOR STREET 2': 1,
    'GUARANTOR SUFFIX': 1,
    'GUARANTOR ZIP': 1,
    'Generic Campaign DISBURSEMENTS': 7,
    'HAWAII': 2,
    'Has filer been designated to make Coordinated Expenditures?': 2,
    'IDAHO': 2,
    'ILLINOIS': 2,
    'INCURRED AMOUNT (This Period)': 517,
    'INDIANA': 2,
    'IOWA': 2,
    'Independent Expenditures': 592,
    'Individual Contribution Total': 90,
    'Individuals': 2,
    'Individuals Itemized': 100,
    'Individuals Total': 98,
    'Individuals Unitemized': 100,
    'Individuals/Persons': 592,
    'Itemized': 592,
    'Itemized Receipts From Persons': 7,
    'Items on Hand to be Liquidated': 2,
    'JOINT FUND PARTICIPANT Committee FEC-ID': 15,
    'JOINT FUND PARTICIPANT Committee NAME': 15,
    'KANSAS': 2,
    'KENTUCKY': 2,
    'LEADERSHIP PAC': 38,
    'LENDER CANDIDATE DISTRICT': 243,
    'LENDER CANDIDATE FIRST NAME': 243,
    'LENDER CANDIDATE ID NUMBER': 243,
    'LENDER CANDIDATE LAST NAME': 243,
    'LENDER CANDIDATE MIDDLE NM': 243,
    'LENDER CANDIDATE OFFICE': 243,
    'LENDER CANDIDATE PREFIX': 243,
    'LENDER CANDIDATE STATE': 243,
    'LENDER CANDIDATE SUFFIX': 243,
    'LENDER CITY': 243,
    'LENDER COMMITTEE ID NUMBER': 243,
    'LENDER FIRST NAME': 243,
    'LENDER LAST NAME': 243,
    'LENDER MIDDLE NAME': 243,
    'LENDER ORGANIZATION NAME': 243,
    'LENDER PREFIX': 243,
    'LENDER STATE': 243,
    'LENDER STREET 1': 243,
    'LENDER STREET 2': 243,
    'LENDER SUFFIX': 243,
    'LENDER ZIP': 243,
    'LEVIN SHARE': 1,
    'LOAN AMOUNT (Original)': 243,
    'LOAN BALANCE': 243,
    'LOAN INTEREST RATE % (Terms)': 243,
    'LOAN PAYMENT TO DATE': 243,
    'LOBBYIST/REGISTRANT PAC': 38,
    'LOUISIANA': 2,
    'Legal and Accounting': 2,
    'Line 4 Total': 7,
    'Loan Repayment By Candidate': 98,
    'Loan Repayments': 592,
    'Loan Repayments Made': 592,
    'Loan Repayments Received': 592,
    'Loan Repayments, ALL Other Loans': 98,
    'Loan Repayments, All Other Loans': 88,
    'Loans Made': 592,
    'Loans made or guarn. by the Candidate': 98,
    'MAINE': 2,
    'MARYLAND': 2,
    'MASSACHUSETTS': 2,
    'MEMO CODE': 546896,
    'MEMO TEXT/DESCRIPTION': 546896,
    'MICHIGAN': 2,
    'MINNESOTA': 2,
    'MISSISSIPPI': 2,
    'MISSOURI': 2,
    'MONTANA': 2,
    'Made or Guaranteed by the Candidate': 2,
    'Made or guaranteed by Candidate': 2,
    'NEBRASKA': 2,
    'NET Operating Expenditures.': 98,
    'NEVADA': 2,
    'NEW HAMPSHIRE': 2,
    'NEW JERSEY': 2,
    'NEW MEXICO': 2,
    'NEW YORK': 2,
    'NON-FEDERAL PERCENTAGE': 1,
    'NONFEDERAL PERCENT': 39,
    'NONFEDERAL PERCENTAGE': 22,
    'NONFEDERAL SHARE': 4951,
    'NORTH CAROLINA': 2,
    'NORTH DAKOTA': 2,
    'Net Contributions': 692,
    'Net Operating Expenditures': 594,
    'Net contributions': 592,
    'Non-Allocable 100% Fed Election Activity': 592,
    'Non-Federal Share': 592,
    'OHIO': 2,
    'OKLAHOMA': 2,
    'OREGON': 2,
    'ORGANIZATION TYPE': 38,
    'ORIGINAL AMENDMENT DATE': 2,
    'OTHER DISBURSEMENTS': 7,
    'OTHER RECEIPTS': 7,
    'Of 51st Contributor': 4,
    'Of Loans made or guar. by the Cand.': 88,
    'Of Orig Registration': 4,
    'Offsets to Operating Expenditures': 690,
    'Offsets to Operating Expenditures (refunds)': 592,
    'Operating': 2,
    'Operating Expenditures': 100,
    'Other Disbursements': 692,
    'Other Federal Operating Expenditures': 592,
    'Other Federal Receipts (dividends)': 592,
    'Other Loans': 2,
    'Other Political Committees': 682,
    'Other Political Committees (PACs)': 594,
    'Other Receipts': 100,
    'Other Repayments': 2,
    'PARTY CODE': 38,
    'PARTY TYPE': 38,
    'PAYEE CANDIDATE DISTRICT': 2,
    'PAYEE CANDIDATE FIRST NAME': 2,
    'PAYEE CANDIDATE ID NUMBER': 2,
    'PAYEE CANDIDATE LAST NAME': 2,
    'PAYEE CANDIDATE MIDDLE NAME': 2,
    'PAYEE CANDIDATE OFFICE': 2,
    'PAYEE CANDIDATE PREFIX': 2,
    'PAYEE CANDIDATE STATE': 2,
    'PAYEE CANDIDATE SUFFIX': 2,
    'PAYEE CITY': 212791,
    'PAYEE COMMITTEE ID NUMBER': 2,
    'PAYEE Committee FEC ID NUMBER': 29,
    'PAYEE FIRST NAME': 212791,
    'PAYEE LAST NAME': 212791,
    'PAYEE MIDDLE NAME': 212791,
    'PAYEE ORGANIZATION NAME': 212791,
    'PAYEE PREFIX': 212791,
    'PAYEE STATE': 212791,
    'PAYEE STREET 1': 212791,
    'PAYEE STREET 2': 212791,
    'PAYEE SUFFIX': 212791,
    'PAYEE ZIP': 212791,
    'PAYMENT AMOUNT (This Period)': 517,
    'PCC CITY': 6,
    'PCC COMMITTEE ID NUMBER': 6,
    'PCC COMMITTEE NAME': 6,
    'PCC STATE': 6,
    'PCC STREET 1': 6,
    'PCC STREET 2': 6,
    'PCC ZIP': 6,
    'PENNSYLVANIA': 2,
    'PUBLIC COMMUNICATIONS REFERENCING PARTY ONLY RATIO APPLIES': 39,
    'PUERTO RICO': 2,
    'PURPOSE OF DEBT OR OBLIGATION': 517,
    'Personal Funds': 243,
    'Political Party Committees': 692,
    'Political Party committees': 592,
    'QTR/MON/POST BUNDLED CONTRIBUTIONS': 1,
    'QUALIFIED COMMITTEE': 592,
    'RATIO CODE': 23,
    'REC TYPE': 1417,
    'RECEIPT DATE': 328,
    'RECEIPT LINE NUMBER': 243,
    'RECEIPTS': 7,
    'RECORD ID NUMBER (for account name)': 7,
    'REPORT CODE': 683,
    'REPORT TYPE (24/48 Hour)': 2,
    'RHODE ISLAND': 2,
    'Received from or Guaranteed by Cand.': 2,
    'Reference to SI or SL system code that identifies the Account': 541672,
    'Refund, Other Political Committees': 98,
    'Refund, Political Party Committees': 98,
    'Refund/Individuals Other than Political Committees': 98,
    'Refund/Other Political Committees': 88,
    'Refund/Political Party Committees': 88,
    'Refunds of Federal Contributions': 592,
    'S/O CANDIDATE DISTRICT': 29,
    'S/O CANDIDATE FIRST NAME': 29,
    'S/O CANDIDATE ID NUMBER': 29,
    'S/O CANDIDATE LAST NAME': 29,
    'S/O CANDIDATE OFFICE': 29,
    'S/O CANDIDATE PREFIX': 29,
    'S/O CANDIDATE STATE': 29,
    'S/O CANDIDATE SUFFIX': 29,
    'S/O CANDINATE MIDDLE NAME': 29,
    'SEMI-ANNUAL BUNDLED CONTRIBS': 1,
    'SEMI-ANNUAL JAN-JUN - Sect 6(b)': 1,
    'SEMI-ANNUAL JUL-DEC - Sect 6(b)': 1,
    'SEMI-ANNUAL PERIOD - Sect 5(c) or (d)': 1,
    'SEMI-ANNUAL REFUNDED BUNDLED AMT': 207808,
    'SIGNATURE FIRST NAME': 38,
    'SIGNATURE LAST NAME': 38,
    'SIGNATURE MIDDLE NAME': 38,
    'SIGNATURE PREFIX': 38,
    'SIGNATURE SUFFIX': 38,
    'SIGNER FIRST NAME': 3,
    'SIGNER LAST NAME': 3,
    'SIGNER MIDDLE NAME': 3,
    'SIGNER PREFIX': 3,
    'SIGNER SUFFIX': 3,
    'SOUTH CAROLINA': 2,
    'SOUTH DAKOTA': 2,
    'STATE': 730,
    'STATE OF ELECTION': 683,
    'STREET 1': 730,
    'STREET 2': 730,
    'SUBORDINATE CITY': 2,
    'SUBORDINATE COMMITTEE ID NUMBER': 2,
    'SUBORDINATE COMMITTEE NAME': 2,
    'SUBORDINATE STATE': 2,
    'SUBORDINATE STREET 1': 2,
    'SUBORDINATE STREET 2': 2,
    'SUBORDINATE ZIP': 2,
    'SUBTOTAL': 7,
    'SUPPORT/OPPOSE CODE': 29,
    'Secured?': 243,
    'Shared Federal Activity (H6) Fed Share': 592,
    'Shared Federal Activity (H6) Non-Fed': 592,
    'State and Local Party Committee Non-Presidential and Non-Senate Election': 39,
    'State and Local Party Committee Presidential and Senate Election Year (36%': 39,
    'State and Local Party Committee Presidential-Only Election Year (28% Federal)': 39,
    'State and Local Party Committee Senate-Only Election Year (21% Federal)': 39,
    'Subtotal': 594,
    'Subtotals': 88,
    'TENNESSEE': 2,
    'TEXAS': 2,
    'TEXT4000': 1417,
    'TOTAL AMOUNT TRANSFERRED': 328,
    'TOTAL DISBURSEMENTS': 7,
    'TOTAL FED-LEVIN AMOUNT': 1,
    'TOTAL FED-NONFED AMOUNT': 4951,
    'TOTAL RECEIPTS': 7,
    'TOTALS': 2,
    'TRANSACTION ID': 333870,
    'TRANSACTION ID NUMBER': 215352,
    'TRANSFERRED AMOUNT': 328,
    'TREASURER CITY': 38,
    'TREASURER FIRST NAME': 727,
    'TREASURER LAST NAME': 727,
    'TREASURER MIDDLE NAME': 727,
    'TREASURER PREFIX': 727,
    'TREASURER STATE': 38,
    'TREASURER STREET 1': 38,
    'TREASURER STREET 2': 38,
    'TREASURER SUFFIX': 727,
    'TREASURER TELEPHONE': 38,
    'TREASURER TITLE': 38,
    'TREASURER ZIP': 38,
    'Terms': 243,
    'The Candidate': 100,
    'Total': 592,
    'Total Contribution Refunds': 690,
    'Total Contributions': 692,
    'Total Contributions (NO Loans)': 88,
    'Total Contributions (No Loans)': 98,
    'Total Contributions Refunds': 692,
    'Total Disbursements': 692,
    'Total Disbursements this Period': 88,
    'Total Federal Disbursements': 592,
    'Total Federal Election Activity': 592,
    'Total Federal Operating Expenditures': 592,
    'Total Federal Receipts': 592,
    'Total Loan Repayments': 98,
    'Total Loan Repayments Made': 2,
    'Total Loans': 100,
    'Total Non-Federal Transfers (18a+18b)': 592,
    'Total Offset to Operating Expenditures': 88,
    'Total Offsets to Operating Expenditures': 100,
    'Total Operating Expenditures': 690,
    'Total Receipts': 692,
    'Total Receipts From Persons': 7,
    'Total Receipts this Period': 88,
    'Total contributions (Other than Loans)': 2,
    'Total contributions Refunds': 592,
    'Total disbursements': 592,
    'Total offsets to Expenditures': 2,
    'Total operating Expenditures': 592,
    'Transfers From Aff/Other Party Committees': 2,
    'Transfers From Other AUTH Committees': 98,
    'Transfers From Other Authorized Committees': 88,
    'Transfers To Other AUTH Committees': 98,
    'Transfers from Affiliated/Other Party Committees': 592,
    'Transfers from Non-Federal (Levin - H5)': 592,
    'Transfers from Nonfederal Account (H3)': 592,
    'Transfers to Affiliated/Other Party Committees': 592,
    'Transfers to Other Authorized Committees': 90,
    'UTAH': 2,
    'Unitemized': 592,
    'Unitemized Receipts From Persons': 7,
    'VERMONT': 2,
    'VIRGIN ISLANDS': 2,
    'VIRGINIA': 2,
    'Voter ID DISBURSEMENTS': 7,
    'Voter Registration DISBURSEMENTS': 7,
    'WASHINGTON': 2,
    'WEST VIRGINIA': 2,
    'WISCONSIN': 2,
    'WYOMING': 2,
    'YEAR OF ELECTION 1900-2999': 6,
    'Year for Above': 592,
    'ZIP': 730,
    '_record_type': 549906,
    '_src_file': 550011}