def load() :
	 return {'name':u'''simple''', 'data'={   'ACCOUNT NAME': 480,
    'ACCOUNT/EVENT IDENTIFIER': 8120,
    'ACTIVITY PRIMARY': 3,
    'ACTIVITY/EVENT NAME': 57,
    'ACTIVITY/EVENT TOTAL YTD': 8131,
    'ADMINISTRATIVE RATIO APPLIES': 65,
    'AFFILIATED CANDIDATE ID NUM': 45,
    'AFFILIATED CITY': 96,
    'AFFILIATED COMMITTEE FEC ID': 4,
    'AFFILIATED COMMITTEE NAME': 4,
    'AFFILIATED Committee ID NUM': 96,
    'AFFILIATED Committee NAME': 96,
    'AFFILIATED FIRST NAME': 96,
    'AFFILIATED LAST NAME': 96,
    'AFFILIATED MIDDLE NAME': 96,
    'AFFILIATED PREFIX': 96,
    'AFFILIATED RELATIONSHIP CODE': 96,
    'AFFILIATED STATE': 96,
    'AFFILIATED STREET 1': 96,
    'AFFILIATED STREET 2': 96,
    'AFFILIATED SUFFIX': 96,
    'AFFILIATED ZIP': 96,
    'AGENT CITY': 96,
    'AGENT FIRST NAME': 96,
    'AGENT LAST NAME': 96,
    'AGENT MIDDLE NAME': 96,
    'AGENT PREFIX': 96,
    'AGENT STATE': 96,
    'AGENT STREET 1': 96,
    'AGENT STREET 2': 96,
    'AGENT SUFFIX': 96,
    'AGENT TELEPHONE': 96,
    'AGENT TITLE': 96,
    'AGENT ZIP': 96,
    'AGGREGATE GENERAL ELEC EXPENDED': 19,
    'ALABAMA': 3,
    'ALASKA': 3,
    'ARIZONA': 3,
    'ARKANSAS': 3,
    'AUTH CITY': 3,
    'AUTH COMMITTEE ID NUMBER': 10,
    'AUTH COMMITTEE NAME': 10,
    'AUTH STATE': 10,
    'AUTH STREET 1': 10,
    'AUTH STREET 2': 10,
    'AUTH ZIP': 10,
    'Activity GOTV': 1,
    'Activity Is Voter ID': 1,
    'Activity Is Voter Registration': 1,
    'Activity is Administrative - Only': 8130,
    'Activity is Direct Candidate Support': 8130,
    'Activity is Direct Fundraising': 8130,
    'Activity is Generic Campaign': 1,
    'Activity is Generic Voter Drive - Only': 8130,
    'Activity is Party Public Communications Made by PAC': 8130,
    'Activity is an Exempt Activity': 8130,
    'All Loans Received': 97,
    'All Other Loans': 22,
    'All Other Political Committees (PACS)': 119,
    'BACK REFERENCE SCHED / FORM NAME': 2987,
    'BACK REFERENCE SCHED NAME': 1440623,
    'BACK REFERENCE TRAN ID': 441,
    'BACK REFERENCE TRAN ID NUMBER': 1446929,
    'BALANCE AT CLOSE (This Period)': 773,
    'BANK CITY': 96,
    'BANK NAME': 96,
    'BANK STATE': 96,
    'BANK STREET 1': 96,
    'BANK STREET 2': 96,
    'BANK ZIP': 96,
    'BEGINNING BALANCE (This Period)': 773,
    'BENEFICIARY CANDIDATE DISTRICT': 550263,
    'BENEFICIARY CANDIDATE FEC ID': 550263,
    'BENEFICIARY CANDIDATE FIRST NAME': 550263,
    'BENEFICIARY CANDIDATE LAST NAME': 550263,
    'BENEFICIARY CANDIDATE MIDDLE NAME': 550263,
    'BENEFICIARY CANDIDATE OFFICE': 550263,
    'BENEFICIARY CANDIDATE PREFIX': 550263,
    'BENEFICIARY CANDIDATE STATE': 550263,
    'BENEFICIARY CANDIDATE SUFFIX': 550263,
    'BENEFICIARY COMMITTEE FEC ID': 550263,
    'BENEFICIARY COMMITTEE NAME': 550263,
    'CALENDAR Y-T-D (per election/office)': 52,
    'CALIFORNIA': 3,
    'CANDIDATE CITY': 7,
    'CANDIDATE DIST': 4,
    'CANDIDATE DISTRICT': 63,
    'CANDIDATE FIRST NAME': 69,
    'CANDIDATE ID NUMBER': 62,
    'CANDIDATE LAST NAME': 69,
    'CANDIDATE MIDDLE NAME': 69,
    'CANDIDATE OFFICE': 69,
    'CANDIDATE PARTY CODE': 7,
    'CANDIDATE PREFIX': 69,
    'CANDIDATE SIGNATURE FIRST NAME': 7,
    'CANDIDATE SIGNATURE LAST NAME': 7,
    'CANDIDATE SIGNATURE MIDDLE NAME': 7,
    'CANDIDATE SIGNATURE PREFIX': 7,
    'CANDIDATE SIGNATURE SUFFIX': 7,
    'CANDIDATE STATE': 69,
    'CANDIDATE STREET 1': 7,
    'CANDIDATE STREET 2': 7,
    'CANDIDATE SUFFIX': 69,
    'CANDIDATE ZIP': 7,
    'CASH ON HAND (Beginning)': 31,
    'CASH ON HAND AT CLOSE ...': 104,
    'CASH ON HAND as of Jan 1': 31,
    'CATEGORY CODE': 558465,
    'CHANGE OF ADDRESS': 1226,
    'CHANGE OF COMMITTEE EMAIL': 55,
    'CHANGE OF COMMITTEE NAME': 55,
    'CHANGE OF COMMITTEE WEB URL': 55,
    'CITY': 1231,
    'COLORADO': 3,
    'COMMITTEE EMAIL': 55,
    'COMMITTEE NAME': 1231,
    'COMMITTEE TYPE': 59,
    'COMMITTEE WEB URL': 55,
    'COMPLETING FIRST NAME': 52,
    'COMPLETING LAST NAME': 52,
    'COMPLETING MIDDLE NAME': 52,
    'COMPLETING PREFIX': 52,
    'COMPLETING SUFFIX': 52,
    'CONDUIT CITY': 1435737,
    'CONDUIT NAME': 1435737,
    'CONDUIT STATE': 1435737,
    'CONDUIT STREET 1': 550263,
    'CONDUIT STREET 2': 550263,
    'CONDUIT STREET1': 885487,
    'CONDUIT STREET2': 885487,
    'CONDUIT ZIP': 1435737,
    'CONNECTICUT': 3,
    'CONTRIBUTION AGGREGATE F3L Semi-annual Bundled': 885487,
    'CONTRIBUTION AMOUNT': 7,
    'CONTRIBUTION AMOUNT (F3L Bundled)': 885487,
    'CONTRIBUTION DATE': 885494,
    'CONTRIBUTION PURPOSE CODE': 212440,
    'CONTRIBUTION PURPOSE DESCRIP': 885487,
    'CONTRIBUTOR CITY': 885494,
    'CONTRIBUTOR COMMITTEE FEC ID': 7,
    'CONTRIBUTOR EMPLOYER': 885494,
    'CONTRIBUTOR FIRST NAME': 885494,
    'CONTRIBUTOR LAST NAME': 885494,
    'CONTRIBUTOR MIDDLE NAME': 885494,
    'CONTRIBUTOR OCCUPATION': 885494,
    'CONTRIBUTOR ORGANIZATION NAME': 885494,
    'CONTRIBUTOR PREFIX': 885494,
    'CONTRIBUTOR STATE': 885494,
    'CONTRIBUTOR STREET 1': 885494,
    'CONTRIBUTOR STREET 2': 885494,
    'CONTRIBUTOR SUFFIX': 885494,
    'CONTRIBUTOR ZIP': 885494,
    'COVERAGE FROM DATE': 1196,
    'COVERAGE THROUGH DATE': 1196,
    'CREDITOR CITY': 773,
    'CREDITOR FIRST NAME': 773,
    'CREDITOR LAST NAME': 773,
    'CREDITOR MIDDLE NAME': 773,
    'CREDITOR ORGANIZATION NAME': 773,
    'CREDITOR PREFIX': 773,
    'CREDITOR STATE': 773,
    'CREDITOR STREET 1': 773,
    'CREDITOR STREET 2': 773,
    'CREDITOR SUFFIX': 773,
    'CREDITOR ZIP': 773,
    'CUSTODIAN CITY': 55,
    'CUSTODIAN FIRST NAME': 55,
    'CUSTODIAN LAST NAME': 55,
    'CUSTODIAN MIDDLE NAME': 55,
    'CUSTODIAN PREFIX': 55,
    'CUSTODIAN STATE': 55,
    'CUSTODIAN STREET 1': 55,
    'CUSTODIAN STREET 2': 55,
    'CUSTODIAN SUFFIX': 55,
    'CUSTODIAN TELEPHONE': 55,
    'CUSTODIAN TITLE': 55,
    'CUSTODIAN ZIP': 55,
    'Cash Beginning Reporting Period': 104,
    'Cash on Hand Beginning Period': 3,
    'Cash on Hand Close': 1057,
    'Cash on Hand Close of Period': 3,
    'Cash on Hand Jan 1, 19': 1057,
    'Cash on Hand at Close': 1057,
    'Cash on Hand beginning': 1057,
    'Cash on hand at Close Period': 104,
    'Cmte Met Requirements': 4,
    'Contributions to Federal Candidates/Committees': 1057,
    'Coordinated Expend made by Party Committees': 1057,
    'DATE OF CONTRIBUTION': 4,
    'DATE OF ELECTION': 1165,
    'DATE SIGNED': 1287,
    'DEBTS BY (Totals from SCH C and/or D)': 104,
    'DEBTS TO ( Totals from SCH C and/or D)': 104,
    'DELAWARE': 3,
    'DESIGNATING COMMITTEE ID NUMBER': 19,
    'DESIGNATING COMMITTEE NAME': 19,
    'DISBURSEMENTS': 31,
    'DIST OF COLUMBIA': 3,
    'DONOR CANDIDATE DISTRICT': 885487,
    'DONOR CANDIDATE FEC ID': 885487,
    'DONOR CANDIDATE FIRST NAME': 885487,
    'DONOR CANDIDATE LAST NAME': 885487,
    'DONOR CANDIDATE MIDDLE NAME': 885487,
    'DONOR CANDIDATE OFFICE': 885487,
    'DONOR CANDIDATE PREFIX': 885487,
    'DONOR CANDIDATE STATE': 885487,
    'DONOR CANDIDATE SUFFIX': 885487,
    'DONOR COMMITTEE FEC ID': 885487,
    'DONOR COMMITTEE NAME': 885487,
    'Date - Day after General Election': 15,
    'Date - General Election': 15,
    'Debts by': 1060,
    'Debts to': 1060,
    'Direct Candidate Support?': 57,
    'Direct Fundraising?': 57,
    'EFFECTIVE DATE': 55,
    'ELECTION CODE': 1437312,
    'ELECTION DISTRICT': 105,
    'ELECTION OTHER DESCRIPTION': 1436178,
    'ELECTION STATE': 105,
    'ENDING CASH ON HAND': 31,
    'ENTITY TYPE': 1445093,
    'EVENT TYPE': 441,
    'EVENT/ACTIVITY ID/NAME': 441,
    'EXPENDITURE AMOUNT': 71,
    'EXPENDITURE AMOUNT (F3L Bundled)': 550263,
    'EXPENDITURE DATE': 558465,
    'EXPENDITURE PURPOSE CODE': 101997,
    'EXPENDITURE PURPOSE DESCRIP': 558465,
    'Exempt Legal & Accounting Disbursement': 3,
    'Expenditures Subject to Limits': 3,
    'FEDERAL PERCENT': 65,
    'FEDERAL PERCENTAGE': 57,
    'FEDERAL SHARE': 8131,
    'FILER CANDIDATE ID NUMBER': 10,
    'FILER COMMITTEE ID': 31,
    'FILER COMMITTEE ID NUMBER': 1449891,
    'FLAT MINIMUM FEDERAL PERCENTAGE': 65,
    'FLORIDA': 3,
    'FORM TYPE': 1446946,
    'Federal Funds': 3,
    'Federal Share': 1057,
    'Fundraising': 3,
    'Fundraising Disbursements': 3,
    'GENERIC CAMPAIGN AMOUNT': 8,
    'GENERIC VOTER DRIVE RATIO APPLIES': 65,
    'GEORGIA': 3,
    'GOTV AMOUNT': 8,
    'GOTV DISBURSEMENTS': 31,
    'GUAM': 3,
    'GUARANTEED AMOUNT': 1,
    'GUARANTOR CITY': 1,
    'GUARANTOR EMPLOYER': 1,
    'GUARANTOR FIRST NAME': 1,
    'GUARANTOR LAST NAME': 1,
    'GUARANTOR MIDDLE NAME': 1,
    'GUARANTOR OCCUPATION': 1,
    'GUARANTOR PREFIX': 1,
    'GUARANTOR STATE': 1,
    'GUARANTOR STREET 1': 1,
    'GUARANTOR STREET 2': 1,
    'GUARANTOR SUFFIX': 1,
    'GUARANTOR ZIP': 1,
    'Generic Campaign DISBURSEMENTS': 31,
    'HAWAII': 3,
    'Has filer been designated to make Coordinated Expenditures?': 19,
    'IDAHO': 3,
    'ILLINOIS': 3,
    'INCURRED AMOUNT (This Period)': 773,
    'INDIANA': 3,
    'IOWA': 3,
    'Independent Expenditures': 1057,
    'Individual Contribution Total': 107,
    'Individuals': 3,
    'Individuals Itemized': 122,
    'Individuals Total': 119,
    'Individuals Unitemized': 122,
    'Individuals/Persons': 1057,
    'Itemized': 1057,
    'Itemized Receipts From Persons': 31,
    'Items on Hand to be Liquidated': 3,
    'JOINT FUND PARTICIPANT Committee FEC-ID': 41,
    'JOINT FUND PARTICIPANT Committee NAME': 41,
    'KANSAS': 3,
    'KENTUCKY': 3,
    'LEADERSHIP PAC': 55,
    'LENDER CANDIDATE DISTRICT': 391,
    'LENDER CANDIDATE FIRST NAME': 391,
    'LENDER CANDIDATE ID NUMBER': 391,
    'LENDER CANDIDATE LAST NAME': 391,
    'LENDER CANDIDATE MIDDLE NM': 391,
    'LENDER CANDIDATE OFFICE': 391,
    'LENDER CANDIDATE PREFIX': 391,
    'LENDER CANDIDATE STATE': 391,
    'LENDER CANDIDATE SUFFIX': 391,
    'LENDER CITY': 391,
    'LENDER COMMITTEE ID NUMBER': 391,
    'LENDER FIRST NAME': 391,
    'LENDER LAST NAME': 391,
    'LENDER MIDDLE NAME': 391,
    'LENDER ORGANIZATION NAME': 391,
    'LENDER PREFIX': 391,
    'LENDER STATE': 391,
    'LENDER STREET 1': 391,
    'LENDER STREET 2': 391,
    'LENDER SUFFIX': 391,
    'LENDER ZIP': 391,
    'LEVIN SHARE': 1,
    'LOAN AMOUNT (Original)': 391,
    'LOAN BALANCE': 391,
    'LOAN INTEREST RATE % (Terms)': 391,
    'LOAN PAYMENT TO DATE': 391,
    'LOBBYIST/REGISTRANT PAC': 55,
    'LOUISIANA': 3,
    'Legal and Accounting': 3,
    'Line 4 Total': 31,
    'Loan Repayment By Candidate': 119,
    'Loan Repayments': 1057,
    'Loan Repayments Made': 1057,
    'Loan Repayments Received': 1057,
    'Loan Repayments, ALL Other Loans': 119,
    'Loan Repayments, All Other Loans': 104,
    'Loans Made': 1057,
    'Loans made or guarn. by the Candidate': 119,
    'MAINE': 3,
    'MARYLAND': 3,
    'MASSACHUSETTS': 3,
    'MEMO CODE': 1444328,
    'MEMO TEXT/DESCRIPTION': 1444328,
    'MICHIGAN': 3,
    'MINNESOTA': 3,
    'MISSISSIPPI': 3,
    'MISSOURI': 3,
    'MONTANA': 3,
    'Made or Guaranteed by the Candidate': 3,
    'Made or guaranteed by Candidate': 3,
    'NEBRASKA': 3,
    'NET Operating Expenditures.': 119,
    'NEVADA': 3,
    'NEW HAMPSHIRE': 3,
    'NEW JERSEY': 3,
    'NEW MEXICO': 3,
    'NEW YORK': 3,
    'NON-FEDERAL PERCENTAGE': 6,
    'NONFEDERAL PERCENT': 65,
    'NONFEDERAL PERCENTAGE': 51,
    'NONFEDERAL SHARE': 8130,
    'NORTH CAROLINA': 3,
    'NORTH DAKOTA': 3,
    'Net Contributions': 1179,
    'Net Operating Expenditures': 1060,
    'Net contributions': 1057,
    'Non-Allocable 100% Fed Election Activity': 1057,
    'Non-Federal Share': 1057,
    'OHIO': 3,
    'OKLAHOMA': 3,
    'OREGON': 3,
    'ORGANIZATION TYPE': 55,
    'ORIGINAL AMENDMENT DATE': 3,
    'OTHER DISBURSEMENTS': 31,
    'OTHER RECEIPTS': 31,
    'Of 51st Contributor': 4,
    'Of Loans made or guar. by the Cand.': 104,
    'Of Orig Registration': 4,
    'Offsets to Operating Expenditures': 1176,
    'Offsets to Operating Expenditures (refunds)': 1057,
    'Operating': 3,
    'Operating Expenditures': 122,
    'Other Disbursements': 1179,
    'Other Federal Operating Expenditures': 1057,
    'Other Federal Receipts (dividends)': 1057,
    'Other Loans': 3,
    'Other Political Committees': 1164,
    'Other Political Committees (PACs)': 1060,
    'Other Receipts': 122,
    'Other Repayments': 3,
    'PARTY CODE': 55,
    'PARTY TYPE': 55,
    'PAYEE CANDIDATE DISTRICT': 19,
    'PAYEE CANDIDATE FIRST NAME': 19,
    'PAYEE CANDIDATE ID NUMBER': 19,
    'PAYEE CANDIDATE LAST NAME': 19,
    'PAYEE CANDIDATE MIDDLE NAME': 19,
    'PAYEE CANDIDATE OFFICE': 19,
    'PAYEE CANDIDATE PREFIX': 19,
    'PAYEE CANDIDATE STATE': 19,
    'PAYEE CANDIDATE SUFFIX': 19,
    'PAYEE CITY': 558465,
    'PAYEE COMMITTEE ID NUMBER': 19,
    'PAYEE Committee FEC ID NUMBER': 52,
    'PAYEE FIRST NAME': 558465,
    'PAYEE LAST NAME': 558465,
    'PAYEE MIDDLE NAME': 558465,
    'PAYEE ORGANIZATION NAME': 558465,
    'PAYEE PREFIX': 558465,
    'PAYEE STATE': 558465,
    'PAYEE STREET 1': 558465,
    'PAYEE STREET 2': 558465,
    'PAYEE SUFFIX': 558465,
    'PAYEE ZIP': 558465,
    'PAYMENT AMOUNT (This Period)': 773,
    'PCC CITY': 7,
    'PCC COMMITTEE ID NUMBER': 7,
    'PCC COMMITTEE NAME': 7,
    'PCC STATE': 7,
    'PCC STREET 1': 7,
    'PCC STREET 2': 7,
    'PCC ZIP': 7,
    'PENNSYLVANIA': 3,
    'PUBLIC COMMUNICATIONS REFERENCING PARTY ONLY RATIO APPLIES': 65,
    'PUERTO RICO': 3,
    'PURPOSE OF DEBT OR OBLIGATION': 773,
    'Personal Funds': 391,
    'Political Party Committees': 1179,
    'Political Party committees': 1057,
    'QTR/MON/POST BUNDLED CONTRIBUTIONS': 1,
    'QUALIFIED COMMITTEE': 1057,
    'RATIO CODE': 57,
    'REC TYPE': 2992,
    'RECEIPT DATE': 449,
    'RECEIPT LINE NUMBER': 391,
    'RECEIPTS': 31,
    'RECORD ID NUMBER (for account name)': 31,
    'REPORT CODE': 1165,
    'REPORT TYPE (24/48 Hour)': 4,
    'RHODE ISLAND': 3,
    'Received from or Guaranteed by Cand.': 3,
    'Reference to SI or SL system code that identifies the Account': 1435737,
    'Refund, Other Political Committees': 119,
    'Refund, Political Party Committees': 119,
    'Refund/Individuals Other than Political Committees': 119,
    'Refund/Other Political Committees': 104,
    'Refund/Political Party Committees': 104,
    'Refunds of Federal Contributions': 1057,
    'S/O CANDIDATE DISTRICT': 52,
    'S/O CANDIDATE FIRST NAME': 52,
    'S/O CANDIDATE ID NUMBER': 52,
    'S/O CANDIDATE LAST NAME': 52,
    'S/O CANDIDATE OFFICE': 52,
    'S/O CANDIDATE PREFIX': 52,
    'S/O CANDIDATE STATE': 52,
    'S/O CANDIDATE SUFFIX': 52,
    'S/O CANDINATE MIDDLE NAME': 52,
    'SEMI-ANNUAL BUNDLED CONTRIBS': 1,
    'SEMI-ANNUAL JAN-JUN - Sect 6(b)': 1,
    'SEMI-ANNUAL JUL-DEC - Sect 6(b)': 1,
    'SEMI-ANNUAL PERIOD - Sect 5(c) or (d)': 1,
    'SEMI-ANNUAL REFUNDED BUNDLED AMT': 550263,
    'SIGNATURE FIRST NAME': 55,
    'SIGNATURE LAST NAME': 55,
    'SIGNATURE MIDDLE NAME': 55,
    'SIGNATURE PREFIX': 55,
    'SIGNATURE SUFFIX': 55,
    'SIGNER FIRST NAME': 3,
    'SIGNER LAST NAME': 3,
    'SIGNER MIDDLE NAME': 3,
    'SIGNER PREFIX': 3,
    'SIGNER SUFFIX': 3,
    'SOUTH CAROLINA': 3,
    'SOUTH DAKOTA': 3,
    'STATE': 1231,
    'STATE OF ELECTION': 1165,
    'STREET 1': 1231,
    'STREET 2': 1231,
    'SUBORDINATE CITY': 19,
    'SUBORDINATE COMMITTEE ID NUMBER': 19,
    'SUBORDINATE COMMITTEE NAME': 19,
    'SUBORDINATE STATE': 19,
    'SUBORDINATE STREET 1': 19,
    'SUBORDINATE STREET 2': 19,
    'SUBORDINATE ZIP': 19,
    'SUBTOTAL': 31,
    'SUPPORT/OPPOSE CODE': 52,
    'Secured?': 391,
    'Shared Federal Activity (H6) Fed Share': 1057,
    'Shared Federal Activity (H6) Non-Fed': 1057,
    'State and Local Party Committee Non-Presidential and Non-Senate Election': 65,
    'State and Local Party Committee Presidential and Senate Election Year (36%': 65,
    'State and Local Party Committee Presidential-Only Election Year (28% Federal)': 65,
    'State and Local Party Committee Senate-Only Election Year (21% Federal)': 65,
    'Subtotal': 1060,
    'Subtotals': 104,
    'TENNESSEE': 3,
    'TEXAS': 3,
    'TEXT4000': 2992,
    'TOTAL AMOUNT TRANSFERRED': 449,
    'TOTAL DISBURSEMENTS': 31,
    'TOTAL FED-LEVIN AMOUNT': 1,
    'TOTAL FED-NONFED AMOUNT': 8130,
    'TOTAL RECEIPTS': 31,
    'TOTALS': 3,
    'TRANSACTION ID': 885487,
    'TRANSACTION ID NUMBER': 563206,
    'TRANSFERRED AMOUNT': 441,
    'TREASURER CITY': 55,
    'TREASURER FIRST NAME': 1228,
    'TREASURER LAST NAME': 1228,
    'TREASURER MIDDLE NAME': 1228,
    'TREASURER PREFIX': 1228,
    'TREASURER STATE': 55,
    'TREASURER STREET 1': 55,
    'TREASURER STREET 2': 55,
    'TREASURER SUFFIX': 1228,
    'TREASURER TELEPHONE': 55,
    'TREASURER TITLE': 55,
    'TREASURER ZIP': 55,
    'Terms': 391,
    'The Candidate': 122,
    'Total': 1057,
    'Total Contribution Refunds': 1176,
    'Total Contributions': 1179,
    'Total Contributions (NO Loans)': 104,
    'Total Contributions (No Loans)': 119,
    'Total Contributions Refunds': 1179,
    'Total Disbursements': 1179,
    'Total Disbursements this Period': 104,
    'Total Federal Disbursements': 1057,
    'Total Federal Election Activity': 1057,
    'Total Federal Operating Expenditures': 1057,
    'Total Federal Receipts': 1057,
    'Total Loan Repayments': 119,
    'Total Loan Repayments Made': 3,
    'Total Loans': 122,
    'Total Non-Federal Transfers (18a+18b)': 1057,
    'Total Offset to Operating Expenditures': 104,
    'Total Offsets to Operating Expenditures': 122,
    'Total Operating Expenditures': 1176,
    'Total Receipts': 1179,
    'Total Receipts From Persons': 31,
    'Total Receipts this Period': 104,
    'Total contributions (Other than Loans)': 3,
    'Total contributions Refunds': 1057,
    'Total disbursements': 1057,
    'Total offsets to Expenditures': 3,
    'Total operating Expenditures': 1057,
    'Transfers From Aff/Other Party Committees': 3,
    'Transfers From Other AUTH Committees': 119,
    'Transfers From Other Authorized Committees': 104,
    'Transfers To Other AUTH Committees': 119,
    'Transfers from Affiliated/Other Party Committees': 1057,
    'Transfers from Non-Federal (Levin - H5)': 1057,
    'Transfers from Nonfederal Account (H3)': 1057,
    'Transfers to Affiliated/Other Party Committees': 1057,
    'Transfers to Other Authorized Committees': 107,
    'UTAH': 3,
    'Unitemized': 1057,
    'Unitemized Receipts From Persons': 31,
    'VERMONT': 3,
    'VIRGIN ISLANDS': 3,
    'VIRGINIA': 3,
    'VOTER ID AMOUNT': 8,
    'VOTER REGISTRATION AMOUNT': 8,
    'Voter ID DISBURSEMENTS': 31,
    'Voter Registration DISBURSEMENTS': 31,
    'WASHINGTON': 3,
    'WEST VIRGINIA': 3,
    'WISCONSIN': 3,
    'WYOMING': 3,
    'YEAR OF ELECTION 1900-2999': 7,
    'Year for Above': 1057,
    'ZIP': 1231,
    '_record_type': 1449853,
    '_src_file': 1450029}